# [한국투자 Open API](https://apiportal.koreainvestment.com/apiservice-summary)

In [2]:
from blsh.kis import kis_auth as ka
from blsh.kis.domestic_stock import domestic_stock_functions as ds

# 인증
# ka.auth(svr="vps")
ka.auth(svr="prod")
trenv = ka.getTREnv()

## **국내주식**
---

### **1. 주문/계좌**

#### 1-1. 주식주문(현금) [v1_국내주식-001]

In [8]:
##############################################################################################
# [국내주식] 주문/계좌 > 주식주문(현금)[v1_국내주식-001]
##############################################################################################
ds.order_cash(env_dv="real", ord_dv="sell", cano=trenv.my_acct, acnt_prdt_cd=trenv.my_prod, pdno="005930",
                    ord_dvsn="00", ord_qty="1", ord_unpr="2000", excg_id_dvsn_cd="SOR")

-------------------------------
Error in response:  200  url= /uapi/domestic-stock/v1/trading/order-cash
rt_cd :  7 / msg_cd :  APBK0919 / msg1 :  장운영일자가 주문일과 상이합니다
-------------------------------

Empty DataFrame
Columns: []
Index: []

#### 1-2. 주식주문(신용) [v1_국내주식-002]

In [9]:
##############################################################################################
# [국내주식] 주문/계좌 > 주식주문(신용)[v1_국내주식-002]
##############################################################################################
ds.order_credit(
    ord_dv="buy",
    cano=trenv.my_acct,
    acnt_prdt_cd=trenv.my_prod,
    pdno="005930",
    crdt_type="21",
    loan_dt="20220810",
    ord_dvsn="00",
    ord_qty="1",
    ord_unpr="55000"
)

-------------------------------
Error in response:  200  url= /uapi/domestic-stock/v1/trading/order-credit
rt_cd :  7 / msg_cd :  APBK2107 / msg1 :  신용 미개설(약정)계좌는 신용주문 불가합니다. (신용계좌유형코드)
-------------------------------

Empty DataFrame
Columns: []
Index: []

#### 1-3. 주식주문(정정취소) [v1_국내주식-003]

In [10]:
##############################################################################################
# [국내주식] 주문/계좌 > 주식주문(정정취소)[v1_국내주식-003]
##############################################################################################
ds.order_rvsecncl(
    env_dv="real",
    cano=trenv.my_acct,
    acnt_prdt_cd=trenv.my_prod,
    krx_fwdg_ord_orgno="06010",
    orgn_odno="0000002101",
    ord_dvsn="00",
    rvse_cncl_dvsn_cd="02",
    ord_qty="1",
    ord_unpr="55000",
    qty_all_ord_yn="Y",
    excg_id_dvsn_cd="KRX"
)

-------------------------------
Error in response:  200  url= /uapi/domestic-stock/v1/trading/order-rvsecncl
rt_cd :  7 / msg_cd :  APBK0344 / msg1 :  원주문정보가 존재하지않습니다.
-------------------------------

Empty DataFrame
Columns: []
Index: []

#### 1-4. 주식정정취소가능주문조회 [v1_국내주식-004]

In [11]:
##############################################################################################
# [국내주식] 주문/계좌 > 주식정정취소가능주문조회[v1_국내주식-004]
##############################################################################################
ds.inquire_psbl_rvsecncl(cano=trenv.my_acct, acnt_prdt_cd=trenv.my_prod, inqr_dvsn_1="1", inqr_dvsn_2="0")

INFO - Data fetch complete.

Empty DataFrame
Columns: []
Index: []

#### 1-5. 주식일별주문체결조회 [v1_국내주식-005]

In [12]:
##############################################################################################
# [국내주식] 주문/계좌 > 주식일별주문체결조회[v1_국내주식-005]
##############################################################################################
result1, result2 = ds.inquire_daily_ccld(
    env_dv="real",
    pd_dv="inner",
    cano=trenv.my_acct,
    acnt_prdt_cd=trenv.my_prod,
    inqr_strt_dt="20220810",
    inqr_end_dt="20220810",
    sll_buy_dvsn_cd="00",
    inqr_dvsn="00",
    pdno="005930",
    ccld_dvsn="00",
    inqr_dvsn_3="00"
)
print(result1)
print(result2)

INFO - Data fetch complete.

Empty DataFrame
Columns: []
Index: []
  tot_ord_qty tot_ccld_qty tot_ccld_amt prsm_tlex_smtl pchs_avg_pric
0           0            0            0              0        0.0000

#### 1-6. 주식예약주문 [v1_국내주식-017]

In [13]:
##############################################################################################
# [국내주식] 주문/계좌 > 주식예약주문[v1_국내주식-017]
##############################################################################################
ds.order_resv(cano=trenv.my_acct, acnt_prdt_cd=trenv.my_prod, pdno="005930", ord_qty="1", ord_unpr="55000",
                    sll_buy_dvsn_cd="02", ord_dvsn_cd="00", ord_objt_cblc_dvsn_cd="10")

  RSVN_ORD_SEQ
0       150927

#### 1-7. 주식예약주문정정취소 [v1_국내주식-018,019]

In [14]:
##############################################################################################
# [국내주식] 주문/계좌 > 주식예약주문정정취소[v1_국내주식-018,019]
##############################################################################################
ds.order_resv_rvsecncl(
    cano=trenv.my_acct,
    acnt_prdt_cd=trenv.my_prod,
    rsvn_ord_seq="88793",
    rsvn_ord_orgno="001",
    rsvn_ord_ord_dt="20250113",
    ord_type="cancel",
    pdno="005930",
    ord_qty="2",
    ord_unpr="55000",
    sll_buy_dvsn_cd="02",
    ord_dvsn_cd="00",
    ord_objt_cblc_dvsn_cd="10"
)

  NRML_PRCS_YN
0            Y

#### 1-8. 주식예약주문조회 [v1_국내주식-020]

In [15]:
##############################################################################################
# [국내주식] 주문/계좌 > 주식예약주문조회[v1_국내주식-020]
##############################################################################################
ds.order_resv_ccnl(
    rsvn_ord_ord_dt="20220729",
    rsvn_ord_end_dt="20220810",
    tmnl_mdia_kind_cd="00",
    cano=trenv.my_acct,
    acnt_prdt_cd=trenv.my_prod,
    prcs_dvsn_cd="0",
    cncl_yn="Y"
)

INFO - Data fetch complete.

Empty DataFrame
Columns: []
Index: []

#### 1-9. 주식잔고조회 [v1_국내주식-006]

In [16]:
##############################################################################################
# [국내주식] 주문/계좌 > 주식잔고조회[v1_국내주식-006]
##############################################################################################
result1, result2 = ds.inquire_balance(
    env_dv="real",
    cano=trenv.my_acct,
    acnt_prdt_cd=trenv.my_prod,
    afhr_flpr_yn="N",
    inqr_dvsn="01",
    unpr_dvsn="01",
    fund_sttl_icld_yn="N",
    fncg_amt_auto_rdpt_yn="N",
    prcs_dvsn="00"
)
print(result1)
print(result2)

INFO - Data fetch complete.

Empty DataFrame
Columns: []
Index: []
  dnca_tot_amt nxdy_excc_amt prvs_rcdl_excc_amt cma_evlu_amt bfdy_buy_amt  \
0            0             0                  0            0            0

  thdt_buy_amt nxdy_auto_rdpt_amt bfdy_sll_amt thdt_sll_amt d2_auto_rdpt_amt  \
0            0                  0            0            0                0

   ... tot_evlu_amt nass_amt fncg_gld_auto_rdpt_yn pchs_amt_smtl_amt  \
0  ...            0        0                                       0

  evlu_amt_smtl_amt evlu_pfls_smtl_amt tot_stln_slng_chgs  \
0                 0                  0                  0

  bfdy_tot_asst_evlu_amt asst_icdc_amt asst_icdc_erng_rt
0                      0             0        0.00000000

[1 rows x 24 columns]

#### 1-10. 주식잔고조회_실현손익 [v1_국내주식-041]

In [17]:
##############################################################################################
# [국내주식] 주문/계좌 > 주식잔고조회_실현손익[v1_국내주식-041]
##############################################################################################
result1, result2 = ds.inquire_balance_rlz_pl(
    cano=trenv.my_acct,
    acnt_prdt_cd=trenv.my_prod,
    afhr_flpr_yn="N",
    inqr_dvsn="02",
    unpr_dvsn="01",
    fund_sttl_icld_yn="N",
    fncg_amt_auto_rdpt_yn="N",
    prcs_dvsn="01",
    cost_icld_yn="N"
)
print(result1)
print(result2)

INFO - Data fetch complete.

Empty DataFrame
Columns: []
Index: []
  dnca_tot_amt nxdy_excc_amt prvs_rcdl_excc_amt cma_evlu_amt bfdy_buy_amt  \
0            0             0                  0            0            0

  thdt_buy_amt nxdy_auto_rdpt_amt bfdy_sll_amt thdt_sll_amt d2_auto_rdpt_amt  \
0            0                  0            0            0                0

   ... evlu_amt_smtl_amt evlu_pfls_smtl_amt tot_stln_slng_chgs  \
0  ...                 0                  0                  0

  bfdy_tot_asst_evlu_amt asst_icdc_amt asst_icdc_erng_rt rlzt_pfls  \
0                      0             0        0.00000000         0

  rlzt_erng_rt real_evlu_pfls real_evlu_pfls_erng_rt
0   0.00000000              0             0.00000000

[1 rows x 28 columns]

#### 1-11. 매수가능조회 [v1_국내주식-007]

In [18]:
##############################################################################################
# [국내주식] 주문/계좌 > 매수가능조회[v1_국내주식-007]
##############################################################################################
ds.inquire_psbl_order(env_dv="real", cano=trenv.my_acct, acnt_prdt_cd=trenv.my_prod, pdno="005930",
                            ord_unpr="55000",
                            ord_dvsn="01", cma_evlu_amt_icld_yn="N", ovrs_icld_yn="N")

,ord_psbl_cash,ord_psbl_sbst,ruse_psbl_amt,fund_rpch_chgs,psbl_qty_calc_unpr,nrcvb_buy_amt,nrcvb_buy_qty,max_buy_amt,max_buy_qty,cma_evlu_amt,ovrs_re_use_amt_wcrc,ord_psbl_frcr_amt_wcrc
0,0,0,0,0,283000,0,0,0,0,0,0,0

#### 1-12. 매도가능수량조회 [국내주식-165]

In [19]:
##############################################################################################
# [국내주식] 주문/계좌 > 매도가능수량조회 [국내주식-165]
##############################################################################################
ds.inquire_psbl_sell(cano=trenv.my_acct, acnt_prdt_cd=trenv.my_prod, pdno="000660")

INFO - Data fetch complete.

,pdno,prdt_name,buy_qty,sll_qty,cblc_qty,nsvg_qty,ord_psbl_qty,pchs_avg_pric,pchs_amt,now_pric,evlu_amt,evlu_pfls_amt,evlu_pfls_rt
0,000660,,0,0,0,0,0,0.0000,0,0,0,0,0.00

#### 1-13. 신용매수가능조회 [v1_국내주식-042]

In [20]:
##############################################################################################
# [국내주식] 주문/계좌 > 신용매수가능조회[v1_국내주식-042]
##############################################################################################
ds.inquire_credit_psamount(
    cano=trenv.my_acct,
    acnt_prdt_cd=trenv.my_prod,
    pdno="005930",
    ord_dvsn="00",
    crdt_type="21",
    cma_evlu_amt_icld_yn="N",
    ovrs_icld_yn="N"
)

-------------------------------
Error in response:  200  url= /uapi/domestic-stock/v1/trading/inquire-credit-psamount
rt_cd :  4 / msg_cd :  APBK1617 / msg1 :  신용계좌만 신용주문가능금액조회가 가능합니다.
-------------------------------

Empty DataFrame
Columns: []
Index: []

#### 1-14. 기간별손익일별합산조회 [v1_국내주식-052]

In [21]:
##############################################################################################
# [국내주식] 주문/계좌 > 기간별손익일별합산조회[v1_국내주식-052]
##############################################################################################
result1, result2 = ds.inquire_period_profit(
    cano=trenv.my_acct,
    acnt_prdt_cd=trenv.my_prod,
    inqr_strt_dt="20230101",
    inqr_end_dt="20240301",
    sort_dvsn="00",
    inqr_dvsn="00",
    cblc_dvsn="00"
)
print(result1)
print(result2)

INFO - Data fetch complete.

Empty DataFrame
Columns: []
Index: []
  sll_qty_smtl sll_tr_amt_smtl sll_fee_smtl sll_tltx_smtl sll_excc_amt_smtl  \
0            0               0            0             0                 0

  buy_qty_smtl buy_tr_amt_smtl buy_fee_smtl buy_tax_smtl buy_excc_amt_smtl  \
0            0               0            0            0                 0

  tot_qty tot_tr_amt tot_fee tot_tltx tot_excc_amt tot_rlzt_pfls loan_int
0       0          0       0        0            0             0        0

#### 1-15. 기간별매매손익현황조회 [v1_국내주식-060]

In [22]:
##############################################################################################
# [국내주식] 주문/계좌 > 기간별매매손익현황조회[v1_국내주식-060]
##############################################################################################
result1, result2 = ds.inquire_period_trade_profit(
    cano=trenv.my_acct,
    acnt_prdt_cd=trenv.my_prod,
    sort_dvsn="02",
    inqr_strt_dt="20230216",
    inqr_end_dt="20240301",
    cblc_dvsn="00"
)
print(result1)
print(result2)

INFO - Data fetch complete.

Empty DataFrame
Columns: []
Index: []
  sll_qty_smtl sll_tr_amt_smtl sll_fee_smtl sll_tltx_smtl sll_excc_amt_smtl  \
0            0               0            0             0                 0

  buyqty_smtl buy_tr_amt_smtl buy_fee_smtl buy_tax_smtl buy_excc_amt_smtl  \
0           0               0            0            0                 0

  tot_qty tot_tr_amt tot_fee tot_tltx tot_excc_amt tot_rlzt_pfls loan_int  \
0       0          0       0        0            0             0        0

    tot_pftrt
0  0.00000000

#### 1-16. 투자계좌자산현황조회 [v1_국내주식-048]

In [23]:
##############################################################################################
# [국내주식] 주문/계좌 > 투자계좌자산현황조회[v1_국내주식-048]
##############################################################################################
result1, result2 = ds.inquire_account_balance(cano=trenv.my_acct, acnt_prdt_cd=trenv.my_prod)
result1
result2

INFO - Data fetch complete.

,pchs_amt_smtl,nass_tot_amt,loan_amt_smtl,evlu_pfls_amt_smtl,evlu_amt_smtl,tot_asst_amt,tot_lnda_tot_ulst_lnda,cma_auto_loan_amt,tot_mgln_amt,stln_evlu_amt,...,cma_evlu_amt,dncl_amt,tot_sbst_amt,thdt_rcvb_amt,ovrs_stck_evlu_amt1,ovrs_bond_evlu_amt,mmf_cma_mgge_loan_amt,sbsc_dncl_amt,pbst_sbsc_fnds_loan_use_amt,etpr_crdt_grnt_loan_amt
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0.000000,0.000000,0,0,0,0

#### 1-17. 주식통합증거금 현황 [국내주식-191]

In [24]:
##############################################################################################
# [국내주식] 주문/계좌 > 주식통합증거금 현황 [국내주식-191]
##############################################################################################
ds.intgr_margin(cano=trenv.my_acct, acnt_prdt_cd=trenv.my_prod, cma_evlu_amt_icld_yn="N", wcrc_frcr_dvsn_cd="01",
                      fwex_ctrt_frcr_dvsn_cd="01")

,acmga_rt,acmga_pct100_aptm_rson,stck_cash_objt_amt,stck_sbst_objt_amt,stck_evlu_objt_amt,stck_ruse_psbl_objt_amt,stck_fund_rpch_chgs_objt_amt,stck_fncg_rdpt_objt_atm,bond_ruse_psbl_objt_amt,stck_cash_use_amt,...,jpy_frst_bltn_exrt,cny_frst_bltn_exrt,uk_usd_re_use_objt_amt,uk_usd_re_use_amt,uk_usd_re_use_oth_mket_use_amt,uk_usd_re_use_ord_psbl_amt,uk_usd_gnrl_ord_psbl_amt,uk_usd_itgr_ord_psbl_amt,hgkg_cny_gnrl_ord_psbl_amt,hgkg_cny_itgr_ord_psbl_amt
0,100.0000,고객100%신청,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,...,9.18390000,209.27000000,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00

#### 1-18. 기간별계좌권리현황조회 [국내주식-211]

In [25]:
##############################################################################################
# [국내주식] 주문/계좌 > 기간별계좌권리현황조회 [국내주식-211]
##############################################################################################
ds.period_rights(inqr_dvsn="01", cano=trenv.my_acct, acnt_prdt_cd=trenv.my_prod, inqr_strt_dt="20260215",
                       inqr_end_dt="20260219")

INFO - Data fetch complete.

Empty DataFrame
Columns: []
Index: []

#### 1-19. 퇴직연금 체결기준잔고 [v1_국내주식-032]

In [26]:
##############################################################################################
# [국내주식] 주문/계좌 > 퇴직연금 체결기준잔고[v1_국내주식-032]
##############################################################################################
result1, result2 = ds.pension_inquire_present_balance(cano=trenv.my_acct, acnt_prdt_cd=trenv.my_prod,
                                                   user_dvsn_cd="00"
                                                   )
print(result1)
print(result2)

-------------------------------
Error in response:  200  url= /uapi/domestic-stock/v1/trading/pension/inquire-present-balance
rt_cd :  7 / msg_cd :  APAC0489 / msg1 :  위탁계좌인 경우만 조회가능합니다.
-------------------------------
Empty DataFrame
Columns: []
Index: []
Empty DataFrame
Columns: []
Index: []

#### 1-20. 퇴직연금 미체결내역 [v1_국내주식-033]

In [27]:
##############################################################################################
# [국내주식] 주문/계좌 > 퇴직연금 미체결내역[v1_국내주식-033]
##############################################################################################
ds.pension_inquire_daily_ccld(cano=trenv.my_acct, acnt_prdt_cd=trenv.my_prod, user_dvsn_cd="%%",
                                    sll_buy_dvsn_cd="00",
                                    ccld_nccs_dvsn="%%", inqr_dvsn_3="00")

INFO - Call Next page...
INFO - Call Next page...
INFO - Call Next page...
INFO - Call Next page...
INFO - Call Next page...
INFO - Call Next page...
INFO - Call Next page...
INFO - Call Next page...
INFO - Call Next page...
INFO - Call Next page...
INFO - Call Next page...
WARNING - Max recursive depth reached.

Empty DataFrame
Columns: []
Index: []

#### 1-21. 퇴직연금 매수가능조회 [v1_국내주식-034]

In [28]:
##############################################################################################
# [국내주식] 주문/계좌 > 퇴직연금 매수가능조회[v1_국내주식-034]
##############################################################################################
ds.pension_inquire_psbl_order(
    cano=trenv.my_acct,
    acnt_prdt_cd=trenv.my_prod,
    pdno="069500",
    acca_dvsn_cd="00",
    cma_evlu_amt_icld_yn="Y",
    ord_unpr="30800",
    ord_dvsn="00"
)

  ord_psbl_cash ruse_psbl_amt psbl_qty_calc_unpr max_buy_amt max_buy_qty
0             0             0              30800           0           0

#### 1-22. 퇴직연금 예수금조회 [v1_국내주식-035]

In [29]:
##############################################################################################
# [국내주식] 주문/계좌 > 퇴직연금 예수금조회[v1_국내주식-035]
##############################################################################################
ds.pension_inquire_deposit(cano=trenv.my_acct, acnt_prdt_cd=trenv.my_prod, acca_dvsn_cd="00")

  dnca_tota nxdy_excc_amt nxdy_sttl_amt nx2_day_sttl_amt
0         0             0             0                0

#### 1-23. 퇴직연금 잔고조회 [v1_국내주식-036]

In [30]:
##############################################################################################
# [국내주식] 주문/계좌 > 퇴직연금 잔고조회[v1_국내주식-036]
##############################################################################################
result1, result2 = ds.pension_inquire_balance(cano=trenv.my_acct, acnt_prdt_cd=trenv.my_prod, acca_dvsn_cd="00",
                                           inqr_dvsn="00")
print(result1)
print(result2)

INFO - Data fetch complete.

Empty DataFrame
Columns: []
Index: []
  dnca_tot_amt nxdy_excc_amt prvs_rcdl_excc_amt thdt_buy_amt thdt_sll_amt  \
0            0             0                  0            0            0

  thdt_tlex_amt scts_evlu_amt tot_evlu_amt
0             0             0            0

### **2. 기본시세**

#### 2-1. 주식현재가 시세 [v1_국내주식-008]

In [3]:
##############################################################################################
# [국내주식] 기본시세 > 주식현재가 시세[v1_국내주식-008]
##############################################################################################
ds.inquire_price(
    env_dv="real",
    fid_cond_mrkt_div_code="J",
    fid_input_iscd="005930"
)

,iscd_stat_cls_code,marg_rate,rprs_mrkt_kor_name,new_hgpr_lwpr_cls_code,bstp_kor_isnm,temp_stop_yn,oprc_rang_cont_yn,clpr_rang_cont_yn,crdt_able_yn,grmn_rate_cls_code,...,cpfn_cnnm,frgn_hldn_qty,vi_cls_code,ovtm_vi_cls_code,last_ssts_cntg_qty,invt_caful_yn,mrkt_warn_cls_code,short_over_yn,sltr_yn,mang_issu_cls_code
0,55,60.00,KOSPI200,신고가,전기·전자,N,N,N,Y,60,...,"7,780 억",2977292115,N,N,585046,N,00,N,N,N

#### 2-2. 주식현재가 체결 [v1_국내주식-009]

In [32]:
##############################################################################################
# [국내주식] 기본시세 > 주식현재가 체결[v1_국내주식-009]
##############################################################################################
ds.inquire_ccnl(
    env_dv="real",
    fid_cond_mrkt_div_code="J",
    fid_input_iscd="005930"
)

,stck_cntg_hour,stck_prpr,prdy_vrss,prdy_vrss_sign,cntg_vol,tday_rltv,prdy_ctrt
0,155946,218000,14500,2,10,116.93,7.13
1,155920,218000,14500,2,30,116.93,7.13
2,155846,218000,14500,2,1,116.93,7.13
3,155749,218000,14500,2,8,116.93,7.13
4,155553,218000,14500,2,99,116.93,7.13
5,155547,218000,14500,2,6,116.93,7.13
6,155500,218000,14500,2,1,116.93,7.13
7,155459,218000,14500,2,4,116.93,7.13
8,155416,218000,14500,2,15,116.93,7.13
9,155327,218000,14500,2,4,116.93,7.13
10,155302,218000,14500,2,2,116.93,7.13
11,155218,218000,14500,2,82,116.93,7.13
12,155138,218000,14500,2,30,116.93,7.13
13,155105,218000,14500,2,110,116.93,7.13
14,155104,218000,14500,2,105,116.94,7.13
15,155059,218000,14500,2,27,116.94,7.13
16,155023,218000,14500,2,60,116.94,7.13
17,154955,218000,14500,2,1,116.94,7.13
18,154948,218000,14500,2,10,116.94,7.13
19,154913,218000,14500,2,5,116.94,7.13
20,154751,218000,14500,2,532,116.94,7.13
21,154739,218000,14500,2,10,116.94,7.13
22,154651,218000,14500,2,1,116.94,7.13
23,154618,218000,14500,2,5,116.94,7.13
24,154614,218000,14500,2,130,116.94,7.13
25,154612,218000,14500,2,2,116.94,7.13
26,154552,218000,14500,2,10,116.94,7.13
27,154540,218000,14500,2,500,116.94,7.13
28,154524,218000,14500,2,10,116.95,7.13
29,154517,218000,14500,2,26,116.95,7.13

#### 2-3. 주식현재가 일자별 [v1_국내주식-010]

In [33]:
##############################################################################################
# [국내주식] 기본시세 > 주식현재가 일자별[v1_국내주식-010]
##############################################################################################
ds.inquire_daily_price(
    env_dv="real",
    fid_cond_mrkt_div_code="J",
    fid_input_iscd="005930",
    fid_period_div_code="D",
    fid_org_adj_prc="0"
)

,stck_bsop_date,stck_oprc,stck_hgpr,stck_lwpr,stck_clpr,acml_vol,prdy_vrss_vol_rate,prdy_vrss,prdy_vrss_sign,prdy_ctrt,hts_frgn_ehrt,frgn_ntby_qty,flng_cls_code,acml_prtt_rate
0,20260226,206500,219000,206000,218000,30095763,11.52,14500,2,7.13,50.66,-8516345,00,1.00
1,20260225,202500,206000,201000,203500,26987996,-3.82,3500,2,1.75,50.80,-9308662,00,1.00
2,20260224,193000,200000,192000,200000,28060617,6.43,7000,2,3.63,50.96,-2095511,00,1.00
3,20260223,194400,197600,190500,193000,26364684,8.88,2900,2,1.53,51.00,-5853598,00,1.00
4,20260220,190000,190300,188600,190100,24213880,-10.48,100,2,0.05,51.09,-12378164,00,1.00
5,20260219,188000,190900,187100,190000,27049388,-21.49,8800,2,4.86,51.30,-7155841,00,1.00
6,20260213,179500,184400,178900,181200,34454192,-16.57,2600,2,1.46,51.42,-5495536,00,1.00
7,20260212,171200,179600,170100,178600,41296011,81.44,10800,2,6.44,51.52,13978186,00,1.00
8,20260211,164000,168600,162000,167800,22760242,17.51,2000,2,1.21,51.28,3534700,00,1.00
9,20260210,167400,168100,165500,165800,19369566,-22.83,-600,5,-0.36,51.22,1884823,00,1.00
10,20260209,168600,168700,165000,166400,25098971,-30.97,7800,2,4.92,51.19,539273,00,1.00
11,20260206,154100,160300,151600,158600,36358081,-5.40,-700,5,-0.44,51.18,-7233442,00,1.00
12,20260205,162000,164000,158500,159300,38435228,28.36,-9800,5,-5.80,51.30,-18518169,00,1.00
13,20260204,163500,169400,163100,169100,29943042,-18.03,1600,2,0.96,51.62,-6002372,00,1.00
14,20260203,157900,167500,157200,167500,36529813,-8.10,17100,2,11.37,51.72,5768588,00,1.00
15,20260202,155700,159600,150400,150400,39748369,-1.99,-10100,5,-6.29,51.62,-7024716,00,1.00
16,20260130,160100,166500,160100,160500,40557267,12.39,-200,5,-0.12,51.74,-3553852,00,1.00
17,20260129,166200,166600,157100,160700,36087223,22.51,-1700,5,-1.05,51.80,-8009722,00,1.00
18,20260128,162600,163300,160200,162400,29456431,0.11,2900,2,1.82,51.93,-2160830,00,1.00
19,20260127,150500,159500,149200,159500,29423670,43.10,7400,2,4.87,51.97,3598195,00,1.00
20,20260126,154900,156400,151500,152100,20561689,-19.07,0,3,0.00,51.91,932006,00,1.00
21,20260123,154700,156000,150100,152100,25407497,-20.78,-200,5,-0.13,51.89,-1910110,00,1.00
22,20260122,155000,157000,150800,152300,32073624,1.17,2800,2,1.87,51.93,400516,00,1.00
23,20260121,141900,149800,141800,149500,31703610,31.77,4300,2,2.96,51.92,7064755,00,1.00
24,20260120,148500,149300,143900,145200,24059218,5.70,-4100,5,-2.75,51.80,-3350092,00,1.00
25,20260119,147200,150600,146600,149300,22762497,-24.13,400,2,0.27,51.86,-291612,00,1.00
26,20260116,145300,149500,144300,148900,30000219,21.45,5000,2,3.47,51.86,637271,00,1.00
27,20260115,139000,144000,138300,143900,24701126,33.92,3600,2,2.57,51.85,264355,00,1.00
28,20260114,137000,140300,136800,140300,18444394,-17.60,2700,2,1.96,51.85,319955,00,1.00
29,20260113,139800,140200,136900,137600,22384699,-14.79,-1200,5,-0.86,51.84,-4287723,00,1.00

#### 2-4. 주식현재가 호가/예상체결 [v1_국내주식-011]

In [34]:
##############################################################################################
# [국내주식] 기본시세 > 주식현재가 호가/예상체결[v1_국내주식-011]
##############################################################################################
ds.inquire_asking_price_exp_ccn(
    env_dv="real",
    fid_cond_mrkt_div_code="J",
    fid_input_iscd="005930"
)

(  aspr_acpt_hour   askp1   askp2   askp3   askp4   askp5   askp6   askp7  \
 0         160000  218500  219000  219500  220000  220500  221000  221500

     askp8   askp9  ... total_askp_rsqn total_bidp_rsqn total_askp_rsqn_icdc  \
 0  222000  222500  ...         1145184         1077626                    0

   total_bidp_rsqn_icdc ovtm_total_askp_icdc ovtm_total_bidp_icdc  \
 0                    0                    0                    0

   ovtm_total_askp_rsqn ovtm_total_bidp_rsqn ntby_aspr_rsqn new_mkop_cls_code
 0                    0                22711         -67558                31

 [1 rows x 71 columns],
   antc_mkop_cls_code stck_prpr stck_oprc stck_hgpr stck_lwpr stck_sdpr  \
 0                112    218000    206500    219000    206000    203500

   antc_cnpr antc_cntg_vrss_sign antc_cntg_vrss antc_cntg_prdy_ctrt antc_vol  \
 0    218000                   2          14500                7.13  2317016

   stck_shrn_iscd vi_cls_code
 0         005930           N  )

#### 2-5. 주식현재가 투자자 [v1_국내주식-012]

In [35]:
##############################################################################################
# [국내주식] 기본시세 > 주식현재가 투자자[v1_국내주식-012]
##############################################################################################
ds.inquire_investor(
    env_dv="real",
    fid_cond_mrkt_div_code="J",
    fid_input_iscd="005930"
)

,stck_bsop_date,stck_clpr,prdy_vrss,prdy_vrss_sign,prsn_ntby_qty,frgn_ntby_qty,orgn_ntby_qty,prsn_ntby_tr_pbmn,frgn_ntby_tr_pbmn,orgn_ntby_tr_pbmn,...,orgn_shnu_vol,prsn_shnu_tr_pbmn,frgn_shnu_tr_pbmn,orgn_shnu_tr_pbmn,prsn_seln_vol,frgn_seln_vol,orgn_seln_vol,prsn_seln_tr_pbmn,frgn_seln_tr_pbmn,orgn_seln_tr_pbmn
0,20260226,218000,14500,2,5011907,-7738139,1604297,1074928,-1663474,347838,...,7852147,2552908,1933755,1687396,6905617,16768692,6247850,1477980,3597228,1339558
1,20260225,203500,3500,2,6242239,-8781657,1393600,1266880,-1785675,285324,...,6631237,1968684,1903306,1350727,3446121,18215618,5237637,701804,3688981,1065403
2,20260224,200000,7000,2,-2406416,-2294251,3776093,-478716,-449640,745652,...,9268279,1408498,2078490,1829641,9560897,12810696,5492186,1887214,2528130,1083989
3,20260223,193000,2900,2,4154406,-5936436,754361,804191,-1147769,144678,...,8066620,1875341,1438722,1560971,5521203,13356662,7312259,1071150,2586492,1416293
4,20260220,190100,100,2,6320615,-10839769,3427880,1197436,-2055002,650707,...,7941484,1921284,922467,1506262,3817945,15702143,4513604,723848,2977469,855555
5,20260219,190000,8800,2,2853975,-5656680,1738080,537180,-1067140,328875,...,7667297,1636009,1788905,1450039,5805592,15118110,5929217,1098828,2856045,1121164
6,20260213,181200,2600,2,3099928,-4715928,556164,561965,-855006,100642,...,8233632,2948793,1572596,1495273,13123426,13384396,7677468,2386828,2427601,1394631
7,20260212,178600,10800,2,-14428111,13526444,244823,-2536881,2385693,34839,...,10417306,1736050,3480524,1838407,24290735,6224313,10172483,4272931,1094831,1803569
8,20260211,167800,2000,2,-4491982,3681106,-49410,-753656,619492,-8793,...,5289293,928154,1789639,877089,10099334,7064479,5338703,1681810,1170147,885882
9,20260210,165800,-600,5,-3616937,1837045,880521,-604582,307309,147294,...,5416640,758035,1384339,903887,8161237,6464260,4536119,1362617,1077030,756592
10,20260209,166400,7800,2,-5964986,510164,4465185,-997473,86565,745783,...,9048972,1093313,1387216,1510776,12515666,7782834,4583787,2090786,1300651,764994
11,20260206,158600,-700,5,3328122,-5705438,1252824,515283,-889137,197646,...,10313343,2339282,1487447,1608197,11713075,15237531,9060519,1824000,2376584,1410551
12,20260205,159300,-9800,5,19450052,-16017134,-4566923,3138983,-2587456,-734610,...,7496816,3955681,797889,1209157,5074394,20977355,12063739,816698,3385345,1943767
13,20260204,169100,1600,2,879319,-5647362,3877159,135465,-933438,649771,...,10291975,1916618,1167159,1716227,10656628,12633122,6414816,1781153,2100597,1066456
14,20260203,167500,17100,2,-8295594,4126708,3575465,-1342096,664792,580850,...,10128822,1733537,2385416,1645030,18949026,10614444,6553357,3075633,1720624,1064180
15,20260202,150400,-10100,5,8730278,-6237202,-3097649,1354695,-969951,-479869,...,9302895,3087260,1450953,1438826,11248505,15683790,12400544,1732565,2420904,1918695
16,20260130,160500,-200,5,1996127,-3669445,1139860,316421,-588349,184876,...,9355327,2228760,2693106,1524503,11700676,20273057,8215467,1912339,3281454,1339627
17,20260129,160700,-1700,5,9140430,-7415509,-1769435,1475759,-1195226,-287799,...,8725997,3196422,1152329,1407375,10658694,14538526,10495432,1720663,2347554,1695173
18,20260128,162400,2900,2,2623324,-1761499,-900399,424331,-284453,-146117,...,6389146,1847232,1845015,1034732,8781380,13140200,7289545,1422901,2129467,1180850
19,20260127,159500,7400,2,-4316139,3490691,827117,-679837,551635,128716,...,6779593,1530187,1936558,1052089,14206861,8960894,5952476,2210025,1384923,923373
20,20260126,152100,0,3,1691743,703937,-2372345,255387,110250,-361914,...,4241177,1292142,1169003,649222,6753492,6922728,6613522,1036755,1058753,1011136
21,20260123,152100,-200,5,2419191,-1729586,-1501383,365835,-265221,-226445,...,6352890,1649618,1108707,976527,8344575,8952792,7854273,1283783,1373929,1202972
22,20260122,152300,2800,2,-2905871,1333121,136101,-450878,208374,20238,...,7219972,1662679,1902384,1113933,13663946,10987613,7083871,2113558,1694010,1093695
23,20260121,149500,4300,2,-8267123,6600000,426468,-1220851,973521,63422,...,6738688,1449201,1973193,996395,18079066,6791669,6312220,2670052,999672,932973
24,20260120,145200,-4100,5,3370500,-2944259,-1963641,489655,-428780,-285984,...,4868106,1902541,643371,711076,9676179,7340941,6831747,1412887,1072150,997060
25,20260119,149300,400,2,-732804,-70936,-741247,-112825,-7191,-109636,...,4927137,1508426,873817,732780,10903547,5942661,5668384,1621251,881008,842416
26,20260116,148900,5000,2,-3575750,811557,1267814,-530029,120909,187206,...,7046891,1668133,1470658,1042605,14871556,9128856,5779077,2198163,1349748,855399
27,20260115,143900,3600,2,-5729556,261224,4001578,-812980,37795,568347,...,8721615,960604,1062344,1236518,12515375,7239489,4720037,1773584,1024549,668172
28,20260114,140300,2700,2,-3550369,152616,1895093,-496193,22728,264048,...,5335626,744089,854659,743319,8897664,5980095,3440533,1240282,831931,479271
29,20260113,137600,-1200,5,2174801,-3772770,-83656,298903,-519984,-11202,...,5012305,1299838,847976,693150,7235448,9894250,5095961,1000935,1367960,704351

#### 2-6. 주식현재가 회원사 [v1_국내주식-013]

In [36]:
##############################################################################################
# [국내주식] 기본시세 > 주식현재가 회원사[v1_국내주식-013]
##############################################################################################
ds.inquire_member(
    env_dv="real",
    fid_cond_mrkt_div_code="J",
    fid_input_iscd="005930"
)

                                                   0
0  {'seln_mbcr_no1': '00033', 'seln_mbcr_no2': '0...

#### 2-7. 국내주식기간별시세(일/주/월/년) [v1_국내주식-016]

In [37]:
##############################################################################################
# [국내주식] 기본시세 > 국내주식기간별시세(일/주/월/년)[v1_국내주식-016]
##############################################################################################
ds.inquire_daily_itemchartprice(
    env_dv="real",
    fid_cond_mrkt_div_code="J",
    fid_input_iscd="005930",
    fid_input_date_1="20250101",
    fid_input_date_2="20260226",
    fid_period_div_code="D",
    fid_org_adj_prc="0"
)

(  prdy_vrss prdy_vrss_sign prdy_ctrt stck_prdy_clpr  acml_vol   acml_tr_pbmn  \
 0     14500              2      7.13         203500  30095763  6451865963088

   hts_kor_isnm stck_prpr stck_shrn_iscd  prdy_vol  ... prdy_vrss_vol vol_tnrt  \
 0         삼성전자    218000         005930  26987996  ...       3107767     0.51

   stck_fcam   lstn_stcn  cpfn  hts_avls    per      eps   pbr  \
 0       100  5919637922  7780  12904811  33.21  6564.00  3.41

   itewhol_loan_rmnd_ratem name
 0                         0.29

 [1 rows x 30 columns],
    stck_bsop_date stck_clpr stck_oprc stck_hgpr stck_lwpr  acml_vol  \
 0        20260226    218000    206500    219000    206000  30095763
 1        20260225    203500    202500    206000    201000  26987996
 2        20260224    200000    193000    200000    192000  28060617
 3        20260223    193000    194400    197600    190500  26364684
 4        20260220    190100    190000    190300    188600  24213880
 ..            ...       ...       ...       ...       ...       ...
 95       20251001     86000     84900     86200     84700  22039361
 96       20250930     83900     84600     84900     83400  16319061
 97       20250929     84200     83300     85000     83200  13069094
 98       20250926     83300     85000     85300     82400  24071193
 99       20250925     86100     84400     86200     84100  19665151

      acml_tr_pbmn flng_cls_code prtt_rate mod_yn prdy_vrss_sign prdy_vrss  \
 0   6451865963088            00      0.00      N              2     14500
 1   5474225346566            00      0.00      N              2      3500
 2   5538097526208            00      0.00      N              2      7000
 3   5107749420482            00      0.00      N              2      2900
 4   4591033033030            00      0.00      N              2       100
 ..            ...           ...       ...    ...            ...       ...
 95  1886160393690            00      0.00      N              2      2100
 96  1371831147850            00      0.00      N              5      -300
 97  1102882949950            00      0.00      N              2       900
 98  2011031686444            00      0.00      N              5     -2800
 99  1683395911552            00      0.00      N              2       700

    revl_issu_reas
 0
 1
 2
 3
 4
 ..            ...
 95
 96
 97
 98
 99

 [100 rows x 13 columns])

#### 2-8. 국내주식업종기간별시세(일_주_월_년) [v1_국내주식-021]

In [38]:
##############################################################################################
# [국내주식] 기본시세 > 국내주식업종기간별시세(일_주_월_년)[v1_국내주식-021]
##############################################################################################
result1, result2 = ds.inquire_daily_indexchartprice(
    fid_cond_mrkt_div_code="J",
    fid_input_iscd="0001",
    fid_input_date_1="20250101",
    fid_input_date_2="20260226",
    fid_period_div_code="D"
)
print(result1)
print(result2)

ERROR - API call failed: OPSQ2001 - ERROR INVALID FID_COND_MRKT_DIV_CODE

-------------------------------
Error in response:  200  url= /uapi/domestic-stock/v1/quotations/inquire-daily-indexchartprice
rt_cd :  2 / msg_cd :  OPSQ2001 / msg1 :  ERROR INVALID FID_COND_MRKT_DIV_CODE
-------------------------------
Empty DataFrame
Columns: []
Index: []
Empty DataFrame
Columns: []
Index: []

#### 2-9. 주식당일분봉조회 [v1_국내주식-022]

In [39]:
##############################################################################################
# [국내주식] 기본시세 > 주식당일분봉조회[v1_국내주식-022]
##############################################################################################
ds.inquire_time_itemchartprice(
    env_dv="real",
    fid_cond_mrkt_div_code="J",
    fid_input_iscd="005930",
    fid_input_hour_1="090000",
    fid_pw_data_incu_yn="N"
)

(  prdy_vrss prdy_vrss_sign prdy_ctrt stck_prdy_clpr  acml_vol   acml_tr_pbmn  \
 0     14500              2      7.13         203500  30095763  6451865963088

   hts_kor_isnm stck_prpr
 0         삼성전자    218000  ,
   stck_bsop_date stck_cntg_hour stck_prpr stck_oprc stck_hgpr stck_lwpr  \
 0       20260226         090000    206500    206500    207500    206500

   cntg_vol  acml_tr_pbmn
 0  1317180  272124200500  )

#### 2-10. 주식현재가 당일시간대별체결 [v1_국내주식-023]

In [40]:
##############################################################################################
# [국내주식] 기본시세 > 주식현재가 당일시간대별체결[v1_국내주식-023]
##############################################################################################
ds.inquire_time_itemconclusion(
    env_dv="real",
    fid_cond_mrkt_div_code="J",
    fid_input_iscd="005930",
    fid_input_hour_1="090000"
)

(  stck_prpr prdy_vrss prdy_vrss_sign prdy_ctrt  acml_vol  prdy_vol  \
 0    218000     14500              2      7.13  30095763  26987996

   rprs_mrkt_kor_name
 0           KOSPI200  ,
   stck_cntg_hour stck_prpr prdy_vrss prdy_vrss_sign prdy_ctrt askp bidp  \
 0         083445    203500         0              3      0.00    0    0
 1         083119    203500         0              3      0.00    0    0
 2         083054    203500         0              3      0.00    0    0
 3         083002    203500         0              3      0.00    0    0

   tday_rltv acml_vol cnqn
 0      0.00       36   20
 1      0.00       16    1
 2      0.00       15    5
 3      0.00       10   10  )

#### 2-11. 주식현재가 시간외시간별체결 [v1_국내주식-025]

In [41]:
##############################################################################################
# [국내주식] 기본시세 > 주식현재가 시간외시간별체결[v1_국내주식-025]
##############################################################################################
ds.inquire_time_overtimeconclusion(
    env_dv="real",
    fid_cond_mrkt_div_code="J",
    fid_input_iscd="005930",
    fid_hour_cls_code="0"
)

(  ovtm_untp_prpr ovtm_untp_prdy_vrss ovtm_untp_prdy_vrss_sign  \
 0         218000                   0                        0

   ovtm_untp_prdy_ctrt ovtm_untp_vol ovtm_untp_tr_pbmn ovtm_untp_mxpr  \
 0                0.00             0                 0         239500

   ovtm_untp_llam ovtm_untp_oprc ovtm_untp_hgpr ovtm_untp_lwpr  \
 0         196500              0              0              0

   ovtm_untp_antc_cnpr ovtm_untp_antc_cntg_vrss ovtm_untp_antc_cntg_vrss_sign  \
 0                   0                        0                             3

   ovtm_untp_antc_cntg_ctrt ovtm_untp_antc_vol uplm_sign lslm_sign
 0                     0.00                  0         1         4  ,
    stck_cntg_hour stck_prpr prdy_vrss prdy_vrss_sign prdy_ctrt    askp  \
 0          155946    218000     14500              2      7.13  218500
 1          155920    218000     14500              2      7.13  218500
 2          155846    218000     14500              2      7.13  218500
 3          155749    218000     14500              2      7.13  218500
 4          155553    218000     14500              2      7.13  218500
 5          155547    218000     14500              2      7.13  218500
 6          155500    218000     14500              2      7.13  218500
 7          155459    218000     14500              2      7.13  218500
 8          155416    218000     14500              2      7.13  218500
 9          155327    218000     14500              2      7.13  218500
 10         155302    218000     14500              2      7.13  218500
 11         155218    218000     14500              2      7.13  218500
 12         155138    218000     14500              2      7.13  218500
 13         155105    218000     14500              2      7.13  218500
 14         155104    218000     14500              2      7.13  218500
 15         155059    218000     14500              2      7.13  218500
 16         155023    218000     14500              2      7.13  218500
 17         154955    218000     14500              2      7.13  218500
 18         154948    218000     14500              2      7.13  218500
 19         154913    218000     14500              2      7.13  218500
 20         154751    218000     14500              2      7.13  218500
 21         154739    218000     14500              2      7.13  218500
 22         154651    218000     14500              2      7.13  218500
 23         154618    218000     14500              2      7.13  218500
 24         154614    218000     14500              2      7.13  218500
 25         154612    218000     14500              2      7.13  218500
 26         154552    218000     14500              2      7.13  218500
 27         154540    218000     14500              2      7.13  218500
 28         154524    218000     14500              2      7.13  218500
 29         154517    218000     14500              2      7.13  218500

       bidp  acml_vol cntg_vol
 0   218000  29904932       10
 1   218000  29904922       30
 2   218000  29904892        1
 3   218000  29904891        8
 4   218000  29904883       99
 5   218000  29904784        6
 6   218000  29904778        1
 7   218000  29904777        4
 8   218000  29904773       15
 9   218000  29904758        4
 10  218000  29904754        2
 11  218000  29904752       82
 12  218000  29904670       30
 13  218000  29904640      110
 14  218000  29904530      105
 15  218000  29904425       27
 16  218000  29904398       60
 17  218000  29904338        1
 18  218000  29904337       10
 19  218000  29904327        5
 20  218000  29904322      532
 21  218000  29903790       10
 22  218000  29903780        1
 23  218000  29903779        5
 24  218000  29903774      130
 25  218000  29903644        2
 26  218000  29903642       10
 27  218000  29903632      500
 28  218000  29903132       10
 29  218000  29903122       26  )

#### 2-12. 주식현재가 시간외일자별주가 [v1_국내주식-026]

In [42]:
##############################################################################################
# [국내주식] 기본시세 > 주식현재가 시간외일자별주가[v1_국내주식-026]
##############################################################################################
ds.inquire_daily_overtimeprice(
    env_dv="real",
    fid_cond_mrkt_div_code="J",
    fid_input_iscd="005930"
)

(  ovtm_untp_prpr ovtm_untp_prdy_vrss ovtm_untp_prdy_vrss_sign  \
 0         218000                   0                        0

   ovtm_untp_prdy_ctrt ovtm_untp_vol ovtm_untp_tr_pbmn ovtm_untp_mxpr  \
 0                0.00             0                 0         239500

   ovtm_untp_llam ovtm_untp_oprc ovtm_untp_hgpr ovtm_untp_lwpr  \
 0         196500              0              0              0

   ovtm_untp_antc_cnpr ovtm_untp_antc_cntg_vrss ovtm_untp_antc_cntg_vrss_sign  \
 0                   0                        0                             3

   ovtm_untp_antc_cntg_ctrt ovtm_untp_antc_vol
 0                     0.00                  0  ,
    stck_bsop_date ovtm_untp_prpr ovtm_untp_prdy_vrss ovtm_untp_prdy_vrss_sign  \
 0        20260226         218000                   0                        0
 1        20260225         203500                   0                        0
 2        20260224         200000                   0                        0
 3        20260223         193000                   0                        0
 4        20260220         190100                   0                        0
 5        20260219         190000                   0                        0
 6        20260213         181200                   0                        0
 7        20260212         178600                   0                        0
 8        20260211         167800                   0                        0
 9        20260210         165800                   0                        0
 10       20260209         166400                   0                        0
 11       20260206         158600                   0                        0
 12       20260205         159300                   0                        0
 13       20260204         169100                   0                        0
 14       20260203         167500                   0                        0
 15       20260202         150400                   0                        0
 16       20260130         160500                   0                        0
 17       20260129         160700                   0                        0
 18       20260128         162400                   0                        0
 19       20260127         159500                   0                        0
 20       20260126         152100                   0                        0
 21       20260123         152100                   0                        0
 22       20260122         152300                   0                        0
 23       20260121         149500                   0                        0
 24       20260120         145200                   0                        0
 25       20260119         149300                   0                        0
 26       20260116         148900                   0                        0
 27       20260115         143900                   0                        0
 28       20260114         140300                   0                        0
 29       20260113         137600                   0                        0

    ovtm_untp_prdy_ctrt ovtm_untp_vol stck_clpr prdy_vrss prdy_vrss_sign  \
 0                 0.00             0    218000     14500              2
 1                 0.00             0    203500      3500              2
 2                 0.00             0    200000      7000              2
 3                 0.00             0    193000      2900              2
 4                 0.00             0    190100       100              2
 5                 0.00             0    190000      8800              2
 6                 0.00             0    181200      2600              2
 7                 0.00             0    178600     10800              2
 8                 0.00             0    167800      2000              2
 9                 0.00             0    165800      -600              5
 10                0.00             0    166400      7800              2
 11                0.00             0    158600      -700              5
 12                0.00             0    159300     -9800              5
 13                0.00             0    169100      1600              2
 14                0.00             0    167500     17100              2
 15                0.00             0    150400    -10100              5
 16                0.00             0    160500      -200              5
 17                0.00             0    160700     -1700              5
 18                0.00             0    162400      2900              2
 19                0.00             0    159500      7400              2
 20                0.00             0    152100         0              3
 21                0.00             0    152100      -200              5
 22                0.00             0    152300      2800              2
 23                0.00             0    149500      4300              2
 24                0.00             0    145200     -4100              5
 25                0.00             0    149300       400              2
 26                0.00             0    148900      5000              2
 27                0.00             0    143900      3600              2
 28                0.00             0    140300      2700              2
 29                0.00             0    137600     -1200              5

    prdy_ctrt  acml_vol ovtm_untp_tr_pbmn
 0       7.13  30095763                 0
 1       1.75  26987996                 0
 2       3.63  28060617                 0
 3       1.53  26364684                 0
 4       0.05  24213880                 0
 5       4.86  27049388                 0
 6       1.46  34454192                 0
 7       6.44  41296011                 0
 8       1.21  22760242                 0
 9      -0.36  19369566                 0
 10      4.92  25098971                 0
 11     -0.44  36358081                 0
 12     -5.80  38435228                 0
 13      0.96  29943042                 0
 14     11.37  36529813                 0
 15     -6.29  39748369                 0
 16     -0.12  40557267                 0
 17     -1.05  36087223                 0
 18      1.82  29456431                 0
 19      4.87  29423670                 0
 20      0.00  20561689                 0
 21     -0.13  25407497                 0
 22      1.87  32073624                 0
 23      2.96  31703610                 0
 24     -2.75  24059218                 0
 25      0.27  22762497                 0
 26      3.47  30000219                 0
 27      2.57  24701126                 0
 28      1.96  18444394                 0
 29     -0.86  22384699                 0  )

#### 2-13. 업종 분봉조회 [v1_국내주식-045]

In [43]:
##############################################################################################
# [국내주식] 기본시세 > 업종 분봉조회[v1_국내주식-045]
##############################################################################################
result1, result2 = ds.inquire_time_indexchartprice(
    fid_cond_mrkt_div_code="J",
    fid_etc_cls_code="0",
    fid_input_iscd="0001",
    fid_input_hour_1="090000",
    fid_pw_data_incu_yn="N"
)
print(result1)
print(result2)

ERROR - API call failed: OPSQ2001 - ERROR INVALID FID_COND_MRKT_DIV_CODE

-------------------------------
Error in response:  200  url= /uapi/domestic-stock/v1/quotations/inquire-time-indexchartprice
rt_cd :  2 / msg_cd :  OPSQ2001 / msg1 :  ERROR INVALID FID_COND_MRKT_DIV_CODE
-------------------------------
Empty DataFrame
Columns: []
Index: []
Empty DataFrame
Columns: []
Index: []

#### 2-14. 주식현재가 시세2 [v1_국내주식-054]

In [44]:
##############################################################################################
# [국내주식] 기본시세 > 주식현재가 시세2[v1_국내주식-054]
##############################################################################################
ds.inquire_price_2(
    fid_cond_mrkt_div_code="J",
    fid_input_iscd="005930"
)

,rprs_mrkt_kor_name,new_hgpr_lwpr_cls_code,insn_pbnt_yn,stck_prpr,prdy_vrss,prdy_vrss_sign,prdy_ctrt,acml_tr_pbmn,acml_vol,prdy_vol,...,new_lstn_cls_name,divi_app_cls_code,short_over_cls_code,vi_cls_code,low_current_yn,ssts_hot_yn,stange_runup_yn,invt_caful_yn,mrkt_warn_cls_code,short_over_yn
0,KOSPI200,신고가,N,218000,14500,2,7.13,6451865963088,30095763,26987996,...,,,,N,N,,N,N,00,N

#### 2-15. 변동성완화장치(VI) 현황 [v1_국내주식-055]

In [45]:
##############################################################################################
# [국내주식] 기본시세 > 변동성완화장치(VI) 현황[v1_국내주식-055]
##############################################################################################
ds.inquire_vi_status(
    fid_div_cls_code="0",
    fid_cond_scr_div_code="20171",
    fid_mrkt_cls_code="K",
    fid_input_iscd="005930",
    fid_rank_sort_cls_code="0",
    fid_input_date_1="20250101",
    fid_trgt_cls_code="111111111",
    fid_trgt_exls_cls_code="0000000000"
)

INFO - Data fetch complete.

Empty DataFrame
Columns: []
Index: []

#### 2-16. 국내주식 시간외현재가 [국내주식-076]

In [46]:
##############################################################################################
# [국내주식] 기본시세 > 국내주식 시간외현재가[국내주식-076]
##############################################################################################
ds.inquire_overtime_price(
    fid_cond_mrkt_div_code="J",
    fid_input_iscd="005930"
)

INFO - Data fetch complete.

,bstp_kor_isnm,ovtm_untp_prpr,ovtm_untp_prdy_vrss,ovtm_untp_prdy_vrss_sign,ovtm_untp_prdy_ctrt,ovtm_untp_vol,ovtm_untp_tr_pbmn,ovtm_untp_mxpr,ovtm_untp_llam,ovtm_untp_oprc,...,mang_issu_yn,mrkt_warn_cls_code,trht_yn,vlnt_deal_cls_name,ovtm_untp_sdpr,insn_pbnt_yn,rprs_mrkt_kor_name,ovtm_vi_cls_code,bidp,askp
0,전기·전자,218000,0,0,0.00,0,0,239500,196500,0,...,N,00,N,,218000,N,KOSPI200,N,218000,218500

#### 2-17. 국내주식 시간외호가 [국내주식-077]

In [47]:
##############################################################################################
# [국내주식] 기본시세 > 국내주식 시간외호가[국내주식-077]
##############################################################################################
ds.inquire_overtime_asking_price(
    fid_cond_mrkt_div_code="J",
    fid_input_iscd="005930"
)

,ovtm_untp_last_hour,ovtm_untp_askp1,ovtm_untp_askp2,ovtm_untp_askp3,ovtm_untp_askp4,ovtm_untp_askp5,ovtm_untp_askp6,ovtm_untp_askp7,ovtm_untp_askp8,ovtm_untp_askp9,...,ovtm_untp_total_bidp_rsqn_icdc,ovtm_untp_ntby_bidp_rsqn,total_askp_rsqn,total_bidp_rsqn,total_askp_rsqn_icdc,total_bidp_rsqn_icdc,ovtm_total_askp_rsqn,ovtm_total_bidp_rsqn,ovtm_total_askp_icdc,ovtm_total_bidp_icdc
0,180000,0,0,0,0,0,0,0,0,0,...,0,0,1145184,1077626,0,0,0,22711,0,0

#### 2-18. 국내주식 호가잔량 순위 [국내주식-089]

In [48]:
##############################################################################################
# [국내주식] 기본시세 > 국내주식 호가잔량 순위[국내주식-089]
##############################################################################################
ds.quote_balance(
    fid_vol_cnt="0",
    fid_cond_mrkt_div_code="J",
    fid_cond_scr_div_code="20171",
    fid_input_iscd="005930",
    fid_rank_sort_cls_code="0",
    fid_div_cls_code="0",
    fid_trgt_cls_code="111111111",
    fid_trgt_exls_cls_code="0000000000",
    fid_input_price_1="0",
    fid_input_price_2="0"
)

ValueError: 조건 화면 분류 코드 확인요망!!!

#### 2-19. 국내주식 시간외잔량 순위 [v1_국내주식-093]

In [ ]:
##############################################################################################
# [국내주식] 기본시세 > 국내주식 시간외잔량 순위[v1_국내주식-093]
##############################################################################################
ds.after_hour_balance(
    fid_input_price_1="0",
    fid_cond_mrkt_div_code="J",
    fid_cond_scr_div_code="20171",
    fid_rank_sort_cls_code="0",
    fid_div_cls_code="0",
    fid_input_iscd="005930",
    fid_trgt_exls_cls_code="0000000000",
    fid_trgt_cls_code="111111111",
    fid_vol_cnt="0",
    fid_input_price_2="0"
)

#### 2-20. 국내주식 장마감 예상체결가 [국내주식-120]

In [ ]:
##############################################################################################
# [국내주식] 기본시세 > 국내주식 장마감 예상체결가[국내주식-120]
##############################################################################################
ds.exp_closing_price(
    fid_cond_mrkt_div_code="J",
    fid_input_iscd="005930",
    fid_rank_sort_cls_code="0",
    fid_cond_scr_div_code="20171",
    fid_blng_cls_code="0"
)

Empty DataFrame
Columns: []
Index: []

#### 2-21. 회원사 실시간 매매동향(틱) [국내주식-163]

In [ ]:
##############################################################################################
# [국내주식] 기본시세 > 회원사 실 시간 매매동향(틱)[국내주식-163]
##############################################################################################
result1, result2 = ds.frgnmem_trade_trend(
    fid_cond_scr_div_code="20171",
    fid_cond_mrkt_div_code="J",
    fid_input_iscd="005930",
    fid_input_iscd_2="00030",
    fid_mrkt_cls_code="K",
    fid_vol_cnt="0"
)
print(result1)
print(result2)

INFO - Data fetch complete.

Empty DataFrame
Columns: []
Index: []
   bsop_hour mbcr_name hts_kor_isnm stck_prpr prdy_vrss prdy_vrss_sign  \
0     153230      삼성증권      영원무역홀딩스    245000     -5000              5
1     153136      삼성증권         태양금속      3025       -25              5
2     153136      삼성증권       롯데정밀화학     50900      -500              5
3     153135      삼성증권     한진중공업홀딩스      5190      -110              5
4     153135      삼성증권        대한항공우     24900      -550              5
..       ...       ...          ...       ...       ...            ...
95    153112      삼성증권         조선선재    110800      2600              2
96    153112      삼성증권          GKL     13270      -360              5
97    153112      삼성증권         영원무역     93000      1000              2
98    153111      삼성증권         이연제약     11140      -230              5
99    153111      삼성증권        인바이오젠      9830      -210              5

   cntg_vol acml_ntby_qty glob_ntby_qty frgn_ntby_qty_icdc
0      -109         -1693          -737              73502
1       180         87121        -74239             -63876
2      1000         11266        -10363               -584
3      1511          6725         -9779              -9779
4       110           180             0               3269
..      ...           ...           ...                ...
95       45           484            -5              62650
96     -140        -29938        -62655             -56952
97    -1281        -12998         -5703              -5294
98        1          8308          -409               1827
99     1439          2182         -2236              -2236

[100 rows x 10 columns]

#### 2-22. 주식일별분봉조회 [국내주식-213]

In [ ]:
##############################################################################################
# [국내주식] 기본시세 > 주식일별분봉조회 [국내주식-213]
##############################################################################################
ds.inquire_time_dailychartprice(
    fid_cond_mrkt_div_code="J",
    fid_input_iscd="005930",
    fid_input_hour_1="090000",
    fid_input_date_1="20260226"
)

(  prdy_vrss prdy_vrss_sign prdy_ctrt stck_prdy_clpr  acml_vol   acml_tr_pbmn  \
 0     14500              2      7.13         203500  30095763  6451865963088

   hts_kor_isnm stck_prpr
 0         삼성전자    218000  ,
   stck_bsop_date stck_cntg_hour stck_prpr stck_oprc stck_hgpr stck_lwpr  \
 0       20260226         090000    206500    206500    207500    206500

   cntg_vol  acml_tr_pbmn
 0  1317180  272124200500  )

### **3. ELW 시세**

#### 3-1. ELW 현재가 시세 [v1_국내주식-014]

In [ ]:
##############################################################################################
# [국내주식] ELW시세 > ELW 현재가 시세 [v1_국내주식-014]
##############################################################################################
ds.inquire_elw_price(
    fid_cond_mrkt_div_code="J",
    fid_input_iscd="005930"
)

### **4. 업종/기타**

#### 4-1. 국내휴장일조회 [국내주식-040]

In [ ]:
##############################################################################################
# [국내주식] 업종/기타 > 국내휴장일조회[국내주식-040]
##############################################################################################
ds.chk_holiday(bass_dt="20260226")

INFO - Call Next page...
INFO - Call Next page...
INFO - Call Next page...
INFO - Call Next page...
INFO - Call Next page...
INFO - Call Next page...
INFO - Call Next page...
INFO - Call Next page...
INFO - Call Next page...
INFO - Call Next page...
INFO - Call Next page...
WARNING - Max recursive depth reached.

      bass_dt wday_dvsn_cd bzdy_yn tr_day_yn opnd_yn sttl_day_yn
0    20260226           05       Y         Y       Y           Y
1    20260227           06       Y         Y       Y           Y
2    20260228           07       N         Y       N           N
3    20260301           01       N         Y       N           N
4    20260302           02       N         Y       N           N
..        ...          ...     ...       ...     ...         ...
259  20261112           05       Y         Y       Y           Y
260  20261113           06       Y         Y       Y           Y
261  20261114           07       N         Y       N           N
262  20261115           01       N         Y       N           N
263  20261116           02       Y         Y       Y           Y

[264 rows x 6 columns]

#### 4-2. 국내업종 현재지수 [v1_국내주식-063]

In [8]:
##############################################################################################
# [국내주식] 업종/기타 > 국내업종 현재지수 [v1_국내주식-063]
##############################################################################################
ds.inquire_index_price(
    fid_cond_mrkt_div_code="J",
    fid_input_iscd="0001"
)

INFO - Data fetch complete.

,bstp_nmix_prpr,bstp_nmix_prdy_vrss,bstp_nmix_prdy_ctrt,acml_vol,prdy_vol,acml_tr_pbmn,prdy_tr_pbmn,bstp_nmix_oprc,prdy_nmix_vrss_nmix_oprc,oprc_vrss_prpr_sign,...,stnr_issu_cnt,down_issu_cnt,lslm_issu_cnt,dryy_hgpr_vrss_prpr_rate,dryy_lwpr_vrss_prpr_rate,total_askp_rsqn,total_bidp_rsqn,seln_rsqn_rate,shnu_rsqn_rate,ntby_rsqn
0,0,0,0.00,0,0,0,0,0,0,3,...,0,0,0,0.00,0.00,0,0,0.00,0.00,0

#### 4-3. 국내업종 시간별지수(초) [국내주식-064]

In [ ]:
##############################################################################################
# [국내주식] 업종/기타 > 국내업종 시간별지수(초)[국내주식-064]
##############################################################################################
ds.inquire_index_tickprice(
    fid_input_iscd="0001",
    fid_cond_mrkt_div_code="J"
)

#### 4-4. 국내업종 일자별지수 [v1_국내주식-065]

In [11]:
##############################################################################################
# [국내주식] 업종/기타 > 국내업종 일자별지수 [v1_국내주식-065]
##############################################################################################
result1, result2 = ds.inquire_index_daily_price(
    fid_period_div_code="D",
    fid_cond_mrkt_div_code="J",
    fid_input_iscd="0001",
    fid_input_date_1="20260226"
)
print(result1)
print(result2)

ERROR - API call failed: OPSQ2001 - ERROR INVALID FID_COND_MRKT_DIV_CODE

-------------------------------
Error in response:  200  url= /uapi/domestic-stock/v1/quotations/inquire-index-daily-price
rt_cd :  2 / msg_cd :  OPSQ2001 / msg1 :  ERROR INVALID FID_COND_MRKT_DIV_CODE
-------------------------------
Empty DataFrame
Columns: []
Index: []
Empty DataFrame
Columns: []
Index: []

#### 4-5. 국내업종 구분별전체시세 [v1_국내주식-066]

In [12]:
##############################################################################################
# [국내주식] 업종/기타 > 국내업종 구분별전체시세[v1_국내주식-066]
##############################################################################################
result1, result2 = ds.inquire_index_category_price(
    fid_cond_mrkt_div_code="J",
    fid_input_iscd="0001",
    fid_cond_scr_div_code="20171",
    fid_mrkt_cls_code="K",
    fid_blng_cls_code="0"
)
print(result1)
print(result2)

ERROR - API call failed: OPSQ2001 - ERROR INVALID FID_COND_MRKT_DIV_CODE

-------------------------------
Error in response:  200  url= /uapi/domestic-stock/v1/quotations/inquire-index-category-price
rt_cd :  2 / msg_cd :  OPSQ2001 / msg1 :  ERROR INVALID FID_COND_MRKT_DIV_CODE
-------------------------------
Empty DataFrame
Columns: []
Index: []
Empty DataFrame
Columns: []
Index: []

#### 4-6. 국내업종 시간별지수(분) [국내주식-119]

In [ ]:
##############################################################################################
# [국내주식] 업종/기타 > 국내업종 시간별지수(분)[국내주식-119]
##############################################################################################
ds.inquire_index_timeprice(
    fid_input_hour_1="090000",
    fid_input_iscd="0001",
    fid_cond_mrkt_div_code="J"
)

#### 4-7. 국내주식 예상체결지수 추이 [국내주식-121]

In [ ]:
##############################################################################################
# [국내주식] 업종/기타 > 국내주식 예상체결지수 추이[국내주식-121]
##############################################################################################
ds.exp_index_trend(
    fid_mkop_cls_code="0",
    fid_input_hour_1="090000",
    fid_input_iscd="0001",
    fid_cond_mrkt_div_code="J"
)

#### 4-8. 국내주식 예상체결 전체지수 [국내주식-122]

In [ ]:
##############################################################################################
# [국내주식] 업종/기타 > 국내주식 예상체결 전체지수[국내주식-122]
##############################################################################################
result1, result2 = ds.exp_total_index(
    fid_mrkt_cls_code="K",
    fid_cond_mrkt_div_code="J",
    fid_cond_scr_div_code="20171",
    fid_input_iscd="0001",
    fid_mkop_cls_code="0"
)
print(result1)
print(result2)

#### 4-9. 금리 종합(국내채권_금리) [국내주식-155]

In [ ]:
##############################################################################################
# [국내주식] 업종/기타 > 금리 종합(국내채권_금리)[국내주식-155]
##############################################################################################
result1, result2 = ds.comp_interest(
    fid_cond_mrkt_div_code="B",
    fid_cond_scr_div_code="20156",
    fid_div_cls_code="0",
    fid_div_cls_code1="0"
)
print(result1)
print(result2)

#### 4-10. 국내선물 영업일조회 [국내주식-160]

In [ ]:
##############################################################################################
# [국내주식] 업종/기타 > 국내선물 영업일조회 [국내주식-160]
##############################################################################################
ds.market_time()

### **5. 종목정보**

#### 5-1. 상품기본조회 [v1_국내주식-029]

In [4]:
##############################################################################################
# [국내주식] 종목정보 > 상품기본조회[v1_국내주식-029]
##############################################################################################
ds.search_info(
    pdno="005930",
    prdt_type_cd="300"
)

INFO - Data fetch complete.

,pdno,prdt_type_cd,prdt_name,prdt_name120,prdt_abrv_name,prdt_eng_name,prdt_eng_name120,prdt_eng_abrv_name,std_pdno,shtn_pdno,prdt_sale_stat_cd,prdt_risk_grad_cd,prdt_clsf_cd,prdt_clsf_name,sale_strt_dt,sale_end_dt,wrap_asst_type_cd,ivst_prdt_type_cd,ivst_prdt_type_cd_name,frst_erlm_dt
0,00000A005930,300,삼성전자보통주,삼성전자보통주,삼성전자,SamsungElectronics,SamsungElectronics,SamsungElec,KR7005930003,005930,,,101010,주권,,,01,1010,주식,

#### 5-2. 주식기본조회 [v1_국내주식-067]

In [ ]:
##############################################################################################
# [국내주식] 종목정보 > 주식기본조회[v1_국내주식-067]
##############################################################################################
ds.search_stock_info(
    prdt_type_cd="300",
    pdno="005930"
)

#### 5-3. 국내주식 대차대조표 [v1_국내주식-078]

In [ ]:
##############################################################################################
# [국내주식] 종목정보 > 국내주식 대차대조표 [v1_국내주식-078]
##############################################################################################
ds.finance_balance_sheet(
    fid_div_cls_code="0",
    fid_cond_mrkt_div_code="J",
    fid_input_iscd="005930"
)

#### 5-4. 국내주식 손익계산서 [v1_국내주식-079]

In [ ]:
##############################################################################################
# [국내주식] 종목정보 > 국내주식 손익계산서 [v1_국내주식-079]
##############################################################################################
ds.finance_income_statement(
    fid_div_cls_code="0",
    fid_cond_mrkt_div_code="J",
    fid_input_iscd="005930"
)

#### 5-5. 국내주식 재무비율 [v1_국내주식-080]

In [ ]:
##############################################################################################
# [국내주식] 종목정보 > 국내주식 재무비율 [v1_국내주식-080]
##############################################################################################
ds.finance_financial_ratio(
    fid_div_cls_code="0",
    fid_cond_mrkt_div_code="J",
    fid_input_iscd="005930"
)

#### 5-6. 국내주식 수익성비율 [v1_국내주식-081]

In [ ]:
##############################################################################################
# [국내주식] 종목정보 > 국내주식 수익성비율[v1_국내주식-081]
##############################################################################################
ds.finance_profit_ratio(
    fid_input_iscd="005930",
    fid_div_cls_code="0",
    fid_cond_mrkt_div_code="J"
)

#### 5-7. 국내주식 기타주요비율 [v1_국내주식-082]

In [ ]:
##############################################################################################
# [국내주식] 종목정보 > 국내주식 기타주요비율[v1_국내주식-082]
##############################################################################################
ds.finance_other_major_ratios(
    fid_input_iscd="005930",
    fid_div_cls_code="0",
    fid_cond_mrkt_div_code="J"
)

#### 5-8. 국내주식 안정성비율 [v1_국내주식-083]

In [ ]:
##############################################################################################
# [국내주식] 종목정보 > 국내주식 안정성비율[v1_국내주식-083]
##############################################################################################
ds.finance_stability_ratio(
    fid_input_iscd="005930",
    fid_div_cls_code="0",
    fid_cond_mrkt_div_code="J"
)

#### 5-9. 국내주식 성장성비율 [v1_국내주식-085]

In [ ]:
##############################################################################################
# [국내주식] 종목정보 > 국내주식 성장성비율 [v1_국내주식-085]
##############################################################################################
ds.finance_growth_ratio(
    fid_input_iscd="005930",
    fid_div_cls_code="0",
    fid_cond_mrkt_div_code="J"
)

#### 5-10. 국내주식 당사 신용가능종목 [국내주식-111]

In [ ]:
##############################################################################################
# [국내주식] 종목정보 > 국내주식 당사 신용가능종목[국내주식-111]
##############################################################################################
ds.credit_by_company(
    fid_rank_sort_cls_code="0",
    fid_slct_yn="Y",
    fid_input_iscd="005930",
    fid_cond_scr_div_code="20171",
    fid_cond_mrkt_div_code="J"
)

#### 5-11. 종합 시황/공시(제목) [국내주식-141]

In [ ]:
##############################################################################################
# [국내주식] 종목정보 > 종합 시황/공시(제목) [국내주식-141]
##############################################################################################
ds.news_title(
    fid_news_ofer_entp_code="",
    fid_cond_mrkt_cls_code="K",
    fid_input_iscd="005930",
    fid_titl_cntt="",
    fid_input_date_1="20250101",
    fid_input_hour_1="090000",
    fid_rank_sort_cls_code="0",
    fid_input_srno="0"
)

#### 5-12. 예탁원정보(유상증자일정) [국내주식-143]

In [ ]:
##############################################################################################
# [국내주식] 종목정보 > 예탁원정보(유상증자일정)[국내주식-143]
##############################################################################################
ds.ksdinfo_paidin_capin(
    cts="",
    gb1="0",
    f_dt="20250101",
    t_dt="20260226",
    sht_cd="005930"
)

#### 5-13. 예탁원정보(무상증자일정) [국내주식-144]

In [ ]:
##############################################################################################
# [국내주식] 종목정보 > 예탁원정보(무상증자일정)[국내주식-144]
##############################################################################################
ds.ksdinfo_bonus_issue(
    cts="",
    f_dt="20250101",
    t_dt="20260226",
    sht_cd="005930"
)

#### 5-14. 예탁원정보(배당일정) [국내주식-145]

In [ ]:
##############################################################################################
# [국내주식] 종목정보 > 예탁원정보(배당일정)[국내주식-145]
##############################################################################################
ds.ksdinfo_dividend(
    cts="",
    gb1="0",
    f_dt="20250101",
    t_dt="20260226",
    sht_cd="005930",
    high_gb="0"
)

#### 5-15. 예탁원정보(주식매수청구일정) [국내주식-146]

In [ ]:
##############################################################################################
# [국내주식] 종목정보 > 예탁원정보(주식매수청구일정)[국내주식-146]
##############################################################################################
ds.ksdinfo_purreq(
    sht_cd="005930",
    t_dt="20260226",
    f_dt="20250101",
    cts=""
)

#### 5-16. 예탁원정보(합병_분할일정) [국내주식-147]

In [ ]:
##############################################################################################
# [국내주식] 종목정보 > 예탁원정보(합병_분할일정)[국내주식-147]
##############################################################################################
ds.ksdinfo_merger_split(
    cts="",
    f_dt="20250101",
    t_dt="20260226",
    sht_cd="005930"
)

#### 5-17. 예탁원정보(액면교체일정) [국내주식-148]

In [ ]:
##############################################################################################
# [국내주식] 종목정보 > 예탁원정보(액면교체일정)[국내주식-148]
##############################################################################################
ds.ksdinfo_rev_split(
    sht_cd="005930",
    cts="",
    f_dt="20250101",
    t_dt="20260226",
    market_gb="K"
)

#### 5-18. 예탁원정보(자본감소일정) [국내주식-149]

In [ ]:
##############################################################################################
# [국내주식] 종목정보 > 예탁원정보(자본감소일정) [국내주식-149]
##############################################################################################
ds.ksdinfo_cap_dcrs(
    cts="",
    f_dt="20250101",
    t_dt="20260226",
    sht_cd="005930"
)

#### 5-19. 예탁원정보(상장정보일정) [국내주식-150]

In [ ]:
##############################################################################################
# [국내주식] 종목정보 > 예탁원정보(상장정보일정)[국내주식-150]
##############################################################################################
ds.ksdinfo_list_info(
    sht_cd="005930",
    t_dt="20260226",
    f_dt="20250101",
    cts=""
)

#### 5-20. 예탁원정보(공모주청약일정) [국내주식-151]

In [ ]:
##############################################################################################
# [국내주식] 종목정보 > 예탁원정보(공모주청약일정)[국내주식-151]
##############################################################################################
ds.ksdinfo_pub_offer(
    sht_cd="005930",
    cts="",
    f_dt="20250101",
    t_dt="20260226"
)

#### 5-21. 예탁원정보(실권주일정) [국내주식-152]

In [ ]:
##############################################################################################
# [국내주식] 종목정보 > 예탁원정보(실권주일정)[국내주식-152]
##############################################################################################
ds.ksdinfo_forfeit(
    sht_cd="005930",
    t_dt="20260226",
    f_dt="20250101",
    cts=""
)

#### 5-22. 예탁원정보(의무예치일정) [국내주식-153]

In [ ]:
##############################################################################################
# [국내주식] 종목정보 > 예탁원정보(의무예치일정) [국내주식-153]
##############################################################################################
ds.ksdinfo_mand_deposit(
    t_dt="20260226",
    sht_cd="005930",
    f_dt="20250101",
    cts=""
)

#### 5-23. 예탁원정보(주주총회일정) [국내주식-154]

In [ ]:
##############################################################################################
# [국내주식] 종목정보 > 예탁원정보(주주총회일정)[국내주식-154]
##############################################################################################
ds.ksdinfo_sharehld_meet(
    cts="",
    f_dt="20250101",
    t_dt="20260226",
    sht_cd="005930"
)

#### 5-24. 국내주식 종목추정실적 [국내주식-187]

In [ ]:
##############################################################################################
# [국내주식] 종목정보 > 국내주식 종목추정실적[국내주식-187]
##############################################################################################
result1, result2 = ds.estimate_perform(
    sht_cd="005930"
)
print(result1)
print(result2)

#### 5-25. 국내주식 종목투자의견 [국내주식-188]

In [ ]:
##############################################################################################
# [국내주식] 종목정보 > 국내주식 종목투자의견[국내주식-188]
##############################################################################################
ds.invest_opinion(
    fid_cond_mrkt_div_code="J",
    fid_cond_scr_div_code="20171",
    fid_input_iscd="005930",
    fid_input_date_1="20250101",
    fid_input_date_2="20260226"
)

#### 5-26. 국내주식 증권사별 투자의견 [국내주식-189]

In [5]:
##############################################################################################
# [국내주식] 종목정보 > 국내주식 증권사별 투자의견[국내주식-189]
##############################################################################################
ds.invest_opbysec(
    fid_cond_mrkt_div_code="J",
    fid_cond_scr_div_code="20171",
    fid_input_iscd="005930",
    fid_div_cls_code="0",
    fid_input_date_1="20250101",
    fid_input_date_2="20260226"
)

INFO - Data fetch complete.

Empty DataFrame
Columns: []
Index: []

#### 5-27. 당사 대주가능 종목 [국내주식-195]

In [11]:
##############################################################################################
# [국내주식] 종목정보 > 당사 대주가능 종목 [국내주식-195]
##############################################################################################
result1, result2 = ds.lendable_by_company(excg_dvsn_cd="00", pdno="", thco_stln_psbl_yn="Y", inqr_dvsn_1="0", ctx_area_fk200="",
                               ctx_area_nk100="")
print(result1)
print(result2)

INFO - Calling next page...
ERROR - API call failed: SYDB0050 - 조회이후에 자료가 변경되었습니다.(다시 조회하세요)

-------------------------------
Error in response:  200  url= /uapi/domestic-stock/v1/quotations/lendable-by-company
rt_cd :  7 / msg_cd :  SYDB0050 / msg1 :  조회이후에 자료가 변경되었습니다.(다시 조회하세요)
-------------------------------
Empty DataFrame
Columns: []
Index: []
Empty DataFrame
Columns: []
Index: []

### **6. 시세분석**

#### 6-1. 국내기관_외국인 매매종목가집계 [국내주식-037]

In [10]:
##############################################################################################
# [국내주식] 시세분석 > 국내기관_외국인 매매종목가집계[국내주식-037]
##############################################################################################
ds.foreign_institution_total(
    fid_cond_mrkt_div_code="V",
    fid_cond_scr_div_code="16449",
    fid_input_iscd="0000",
    fid_div_cls_code="0",
    fid_rank_sort_cls_code="0",
    fid_etc_cls_code="0"
)

INFO - Data fetch complete.

,hts_kor_isnm,mksc_shrn_iscd,ntby_qty,stck_prpr,prdy_vrss_sign,prdy_vrss,prdy_ctrt,acml_vol,frgn_ntby_qty,orgn_ntby_qty,...,etc_corp_ntby_vol,frgn_ntby_tr_pbmn,orgn_ntby_tr_pbmn,ivtr_ntby_tr_pbmn,bank_ntby_tr_pbmn,insu_ntby_tr_pbmn,mrbn_ntby_tr_pbmn,fund_ntby_tr_pbmn,etc_orgt_ntby_tr_pbmn,etc_corp_ntby_tr_pbmn
0,대우건설,047040,2001000,10140,2,90,0.90,17508679,2281000,-226000,...,-54000,23129,-2292,-1734,-91,-446,0,-20,0,-548
1,카카오,035720,1909000,62300,2,900,1.47,7242478,1573000,293000,...,43000,97998,18254,12958,0,2118,0,3177,0,2679
2,삼성중공업,010140,1470000,28950,2,250,0.87,5960960,1376000,43000,...,51000,39835,1245,2027,58,-463,0,-376,0,1476
3,신성이엔지,011930,1452000,2450,2,315,14.75,84274249,1440000,8000,...,4000,3528,20,-201,0,0,0,221,0,10
4,현대제철,004020,1281000,46500,2,7700,19.85,11952358,1342000,-76000,...,15000,62403,-3534,-1163,558,-977,0,-1953,0,698
5,아주IB투자,027360,1036000,5810,1,1340,29.98,26653721,1017000,0,...,19000,5909,0,0,0,0,0,0,0,110
6,이수페타시스,007660,892000,127600,2,9100,7.68,3010461,850000,44000,...,-2000,108460,5614,3318,-128,128,0,2297,0,-255
7,두산에너빌리티,034020,883000,106300,2,2500,2.41,8296804,821000,41000,...,21000,87272,4358,532,0,0,0,3827,0,2232
8,미래에셋증권,006800,866000,72000,5,-1600,-2.17,6845378,815000,28000,...,23000,58680,2016,1152,72,-1080,0,1872,0,1656
9,팬오션,028670,846000,5280,5,-20,-0.38,3757724,896000,-63000,...,13000,4731,-333,-312,0,-21,0,0,0,69
10,현대로템,064350,792000,230500,2,10500,4.77,1829137,772000,31000,...,-11000,177946,7146,5302,-231,461,0,1614,0,-2536
11,제이알글로벌리츠,348950,629000,1881,5,-37,-1.93,3309771,1025000,-93000,...,-303000,1928,-175,-134,0,-23,0,-19,0,-570
12,LG화학,051910,527000,417500,2,27500,7.05,1146026,455000,71000,...,1000,189963,29643,18788,0,418,0,10438,0,418
13,KEC,092220,454000,1305,2,55,4.40,5819248,469000,0,...,-15000,612,0,0,0,0,0,0,0,-20
14,대한전선,001440,395000,36000,2,650,1.84,8482122,406000,-4000,...,-7000,14616,-144,-72,0,0,0,-72,0,-252
15,아난티,025980,393000,8600,2,400,4.88,4028507,363000,19000,...,11000,3122,163,163,0,0,0,0,0,95
16,클로봇,466100,364000,74200,2,1700,2.34,1171500,348000,0,...,16000,25822,0,0,0,0,0,0,0,1187
17,한화투자증권,003530,327000,8340,5,-190,-2.23,7162652,262000,68000,...,-3000,2185,567,567,0,0,0,0,0,-25
18,대원전선,006340,325000,6790,2,380,5.93,48026671,271000,42000,...,12000,1840,285,285,0,0,0,0,0,81
19,태성,323280,324000,79000,2,8500,12.06,846785,325000,0,...,-1000,25675,0,0,0,0,0,0,0,-79
20,지아이이노베이션,358570,318000,16140,2,850,5.56,1118730,314000,0,...,4000,5068,0,0,0,0,0,0,0,65
21,HJ중공업,097230,318000,25300,2,100,0.40,2554742,319000,-1000,...,0,8071,-25,0,-25,0,0,0,0,0
22,성우하이텍,015750,298000,8880,2,240,2.78,2032762,289000,16000,...,-7000,2566,142,142,0,0,0,0,0,-62
23,코웨이,021240,295000,81900,5,-2200,-2.62,7067695,279000,15000,...,1000,22850,1229,-410,0,-82,0,1720,0,82
24,현대지에프홀딩스,005440,294000,16000,5,-610,-3.67,1379602,276000,-55000,...,73000,4416,-880,-768,-704,-160,0,752,0,1168
25,케이바이오,038530,289000,377,5,-15,-3.83,6989667,289000,0,...,0,109,0,0,0,0,0,0,0,0
26,신한지주,055550,285000,96900,5,-3000,-3.00,3007690,379000,-31000,...,-63000,36725,-3004,-1454,0,0,0,-1550,0,-6105
27,부광약품,003000,280000,5610,2,330,6.25,6165870,208000,64000,...,8000,1167,359,-22,0,0,0,381,0,45
28,화신,010690,277000,15530,2,1580,11.33,2528179,123000,147000,...,7000,1910,2283,2283,0,0,0,0,0,109
29,좋은사람들,033340,273000,2085,2,75,3.73,14829627,271000,0,...,2000,565,0,0,0,0,0,0,0,4

#### 6-2. 종목조건검색 목록조회 [국내주식-038]

In [ ]:
##############################################################################################
# [국내주식] 시세분석 > 종목조건검색 목록조회[국내주식-038]
##############################################################################################
ds.psearch_title(user_id=trenv.my_htsid)

-------------------------------
Error in response:  200  url= /uapi/domestic-stock/v1/quotations/psearch-title
rt_cd :  1 / msg_cd :  MCA05762 / msg1 :  조회가 계속 됩니다. (다음을 누르십시오.)
-------------------------------

Empty DataFrame
Columns: []
Index: []

#### 6-3. 종목조건검색조회 [국내주식-039]

In [ ]:
##############################################################################################
# [국내주식] 시세분석 > 종목조건검색조회 [국내주식-039]
##############################################################################################
ds.psearch_result(
    user_id=trenv.my_id,
    seq="1"
)

#### 6-4. 종목별 프로그램매매추이(체결) [v1_국내주식-044]

In [ ]:
##############################################################################################
# [국내주식] 시세분석 > 종목별 프로그램매매추이(체결)[v1_국내주식-044]
##############################################################################################
ds.program_trade_by_stock(
    fid_cond_mrkt_div_code="J",
    fid_input_iscd="005930"
)

#### 6-5. 종목별 외인기관 추정가집계 [v1_국내주식-046]

In [ ]:
##############################################################################################
# [국내주식] 시세분석 > 종목별 외인기관 추정가집계[v1_국내주식-046]
##############################################################################################
ds.investor_trend_estimate(
    mksc_shrn_iscd="005930"
)

#### 6-6. 종목별일별매수매도체결량 [v1_국내주식-056]

In [ ]:
##############################################################################################
# [국내주식] 시세분석 > 종목별일별매수매도체결량 [v1_국내주식-056]
##############################################################################################
ds.inquire_daily_trade_volume(
    fid_cond_mrkt_div_code="J",
    fid_input_iscd="005930",
    fid_period_div_code="D"
)

#### 6-7. 시장별 투자자매매동향(시세) [v1_국내주식-074]

In [ ]:
##############################################################################################
# [국내주식] 시세분석 > 시장별 투자자매매동향(시세)[v1_국내주식-074]
##############################################################################################
ds.inquire_investor_time_by_market(
    fid_input_iscd="0001",
    fid_input_iscd_2="0002"
)

#### 6-8. 시장별 투자자매매동향(일별) [국내주식-075]

In [ ]:
##############################################################################################
# [국내주식] 시세분석 > 시장별 투자자매매동향(일별) [국내주식-075]
##############################################################################################
ds.inquire_investor_daily_by_market(
    fid_cond_mrkt_div_code="J",
    fid_input_iscd="0001",
    fid_input_date_1="20250101",
    fid_input_iscd_1="0001",
    fid_input_date_2="20260226",
    fid_input_iscd_2="0002"
)

#### 6-9. 국내주식 신용잔고 일별추이 [국내주식-110]

In [ ]:
##############################################################################################
# [국내주식] 시세분석 > 국내주식 신용잔고 일별추이[국내주식-110]
##############################################################################################
ds.daily_credit_balance(
    fid_cond_mrkt_div_code="J",
    fid_cond_scr_div_code="20171",
    fid_input_iscd="005930",
    fid_input_date_1="20250101"
)

#### 6-10. 종목별 프로그램매매추이(일별) [국내주식-113]

In [ ]:
##############################################################################################
# [국내주식] 시세분석 > 종목별 프로그램매매추이(일별) [국내주식-113]
##############################################################################################
ds.program_trade_by_stock_daily(
    fid_cond_mrkt_div_code="J",
    fid_input_iscd="005930"
)

#### 6-11. 프로그램매매 종합현황(시간) [국내주식-114]

In [ ]:
##############################################################################################
# [국내주식] 시세분석 > 프로그램매매 종합현황(시간) [국내주식-114]
##############################################################################################
ds.comp_program_trade_today(
    fid_cond_mrkt_div_code="J",
    fid_mrkt_cls_code="K"
)

#### 6-12. 프로그램매매 종합현황(일별) [국내주식-115]

In [ ]:
##############################################################################################
# [국내주식] 시세분석 > 프로그램매매 종합현황(일별)[국내주식-115]
##############################################################################################
ds.comp_program_trade_daily(
    fid_cond_mrkt_div_code="J",
    fid_mrkt_cls_code="K"
)

#### 6-13. 프로그램매매 투자자매매동향(당일) [국내주식-116]

In [ ]:
##############################################################################################
# [국내주식] 시세분석 > 프로그램매매 투자자매매동향(당일) [국내주식-116]
##############################################################################################
ds.investor_program_trade_today(
    mrkt_div_cls_code="K"
)

#### 6-14. 국내주식 예상체결가 추이 [국내주식-118]

In [ ]:
##############################################################################################
# [국내주식] 시세분석 > 국내주식 예상체결가 추이[국내주식-118]
##############################################################################################
ds.exp_price_trend(
    fid_cond_mrkt_div_code="J",
    fid_input_iscd="005930",
    fid_mkop_cls_code="0"
)

#### 6-15. 국내주식 공매도 일별추이 [국내주식-134]

In [ ]:
##############################################################################################
# [국내주식] 시세분석 > 국내주식 공매도 일별추이[국내주식-134]
##############################################################################################
ds.daily_short_sale(
    fid_cond_mrkt_div_code="J",
    fid_input_iscd="005930"
)

#### 6-16. 종목별 일별 대차거래추이 [국내주식-135]

In [ ]:
##############################################################################################
# [국내주식] 시세분석 > 종목별 일별 대차거래추이 [국내주식-135]
##############################################################################################
ds.daily_loan_trans(
    mrkt_div_cls_code="K",
    mksc_shrn_iscd="005930"
)

#### 6-17. 국내주식 시간외거래량순위 [국내주식-139]

In [ ]:
##############################################################################################
# [국내주식] 국내주식 > 국내주식 시간외거래량순위[국내주식-139]
##############################################################################################
result1, result2 = ds.overtime_volume(
    fid_cond_mrkt_div_code="J",
    fid_cond_scr_div_code="20171",
    fid_input_iscd="005930",
    fid_rank_sort_cls_code="0",
    fid_input_price_1="0",
    fid_input_price_2="0",
    fid_vol_cnt="0",
    fid_trgt_cls_code="111111111",
    fid_trgt_exls_cls_code="0000000000"
)
print(result1)
print(result2)

#### 6-18. 국내주식 시간외예상체결등락률 [국내주식-140]

In [ ]:
##############################################################################################
# [국내주식] 시세분석 > 국내주식 시간외예상체결등락률 [국내주식-140]
##############################################################################################
ds.overtime_exp_trans_fluct(
    fid_cond_mrkt_div_code="J",
    fid_cond_scr_div_code="20171",
    fid_input_iscd="005930",
    fid_rank_sort_cls_code="0",
    fid_div_cls_code="0"
)

#### 6-19. 외국계 매매종목 가집계 [국내주식-161]

In [ ]:
##############################################################################################
# [국내주식] 시세분석 > 외국계 매매종목 가집계 [국내주식-161]
##############################################################################################
ds.frgnmem_trade_estimate(
    fid_cond_mrkt_div_code="J",
    fid_cond_scr_div_code="20171",
    fid_input_iscd="005930",
    fid_rank_sort_cls_code="0",
    fid_rank_sort_cls_code_2="0"
)

#### 6-20. 종목별 외국계 순매수추이 [국내주식-164]

In [ ]:
##############################################################################################
# [국내주식] 시세분석 > 종목별 외국계 순매수추이 [국내주식-164]
##############################################################################################
ds.frgnmem_pchs_trend(
    fid_cond_mrkt_div_code="J",
    fid_input_iscd="005930",
    fid_input_iscd_2="00030"
)

#### 6-21. 국내주식 상하한가 포착 [국내주식-190]

In [ ]:
##############################################################################################
# [국내주식] 시세분석 > 국내주식 상하한가 포착 [국내주식-190]
##############################################################################################
ds.capture_uplowprice(
    fid_cond_mrkt_div_code="J",
    fid_cond_scr_div_code="20171",
    fid_prc_cls_code="0",
    fid_div_cls_code="0",
    fid_input_iscd="005930"
)

#### 6-22. 국내주식 체결금액별 매매비중 [국내주식-192]

In [ ]:
##############################################################################################
# [국내주식] 시세분석 > 국내주식 체결금액별 매매비중 [국내주식-192]
##############################################################################################
ds.tradprt_byamt(
    fid_cond_mrkt_div_code="J",
    fid_cond_scr_div_code="20171",
    fid_input_iscd="005930"
)

#### 6-23. 국내 증시자금 종합 [국내주식-193]

In [ ]:
##############################################################################################
# [국내주식] 시세분석 > 국내 증시자금 종합 [국내주식-193]
##############################################################################################
ds.mktfunds()

#### 6-24. 국내주식 매물대/거래비중 [국내주식-196]

In [ ]:
##############################################################################################
# [국내주식] 시세분석 > 국내주식 매물대/거래비중 [국내주식-196]
##############################################################################################
ds.pbar_tratio(
    fid_cond_mrkt_div_code="J",
    fid_input_iscd="005930",
    fid_cond_scr_div_code="20171"
)

#### 6-25. 주식현재가 회원사 종목매매동향 [국내주식-197]

In [ ]:
##############################################################################################
# [국내주식] 시세분석 > 주식현재가 회원사 종목매매동향 [국내주식-197]
##############################################################################################
ds.inquire_member_daily(
    fid_cond_mrkt_div_code="J",
    fid_input_iscd="005930",
    fid_input_iscd_2="00030",
    fid_input_date_1="20250101",
    fid_input_date_2="20260226"
)

#### 6-26. 관심종목 그룹별 종목조회 [국내주식-203]

In [ ]:
##############################################################################################
# [국내주식] 시세분석 > 관심종목 그룹별 종목조회 [국내주식-203]
##############################################################################################
result1, result2 = ds.intstock_stocklist_by_group(
    type="1",
    user_id=trenv.my_htsid,
    inter_grp_code="001",
    fid_etc_cls_code="4"
)
print(result1)
print(result2)

#### 6-27. 관심종목 그룹조회 [국내주식-204]

In [ ]:
##############################################################################################
# [국내주식] 시세분석 > 관심종목 그룹조회 [국내주식-204]
##############################################################################################
ds.intstock_grouplist(
    type="1",
    fid_etc_cls_code="0",
    user_id=trenv.my_id
)

#### 6-28. 관심종목(멀티종목) 시세조회 [국내주식-205]

In [3]:
##############################################################################################
# [국내주식] 시세분석 > 관심종목(멀티종목) 시세조회 [국내주식-205]
##############################################################################################
ds.intstock_multprice(
    fid_cond_mrkt_div_code_1="J",
    fid_input_iscd_1="419530",
    fid_cond_mrkt_div_code_2="J",
    fid_input_iscd_2="092070"
)

INFO - Data fetch complete.

,kospi_kosdaq_cls_name,mrkt_trtm_cls_name,hour_cls_code,inter_shrn_iscd,inter_kor_isnm,inter2_prpr,inter2_prdy_vrss,prdy_vrss_sign,prdy_ctrt,acml_vol,...,total_askp_rsqn,total_bidp_rsqn,acml_tr_pbmn,inter2_prdy_clpr,oprc_vrss_hgpr_rate,intr_antc_cntg_vrss,intr_antc_cntg_vrss_sign,intr_antc_cntg_prdy_ctrt,intr_antc_vol,inter2_sdpr
0,,,0,419530,SAMG엔터,35150,-650,5,-1.82,85512,...,1670,7396,2999238350,35800,0.00,0,3,0.00,0,35800
1,,,0,092070,디엔에프,22100,-700,5,-3.07,170809,...,5051,13075,3755956950,22800,1.10,0,3,0.00,0,22800

#### 6-29. 종목별 투자자매매동향(일별) [종목별 투자자매매동향(일별)]

In [ ]:
##############################################################################################
# [국내주식] 시세분석  > 종목별 투자자매매동향(일별)[종목별 투자자매매동향(일별)]
##############################################################################################
result1, result2 = ds.investor_trade_by_stock_daily(
    fid_cond_mrkt_div_code="J",
    fid_input_iscd="005930",
    fid_input_date_1="20250101",
    fid_org_adj_prc="0",
    fid_etc_cls_code="0"
)
print(result1)
print(result2)

### **7. 순위분석**

#### 7-1. 거래량순위 [v1_국내주식-047]

In [21]:
##############################################################################################
# [국내주식] 순위분석 > 거래량순위[v1_국내주식-047]
##############################################################################################
ds.volume_rank(
    fid_cond_mrkt_div_code="J",
    fid_cond_scr_div_code="20171",
    fid_input_iscd="005930",
    fid_div_cls_code="0",
    fid_blng_cls_code="0",
    fid_trgt_cls_code="111111111",
    fid_trgt_exls_cls_code="0000000000",
    fid_input_price_1="0",
    fid_input_price_2="0",
    fid_vol_cnt="0",
    fid_input_date_1="20260226"
)

The End

Empty DataFrame
Columns: []
Index: []

#### 7-2. 등락률 순위 [v1_국내주식-088]

In [ ]:
##############################################################################################
# [국내주식] 순위분석 > 등락률 순위[v1_국내주식-088]
##############################################################################################
ds.fluctuation(
    fid_cond_mrkt_div_code="J",
    fid_cond_scr_div_code="20171",
    fid_input_iscd="005930",
    fid_rank_sort_cls_code="0",
    fid_input_cnt_1="0",
    fid_prc_cls_code="0",
    fid_input_price_1="0",
    fid_input_price_2="0",
    fid_vol_cnt="0",
    fid_trgt_cls_code="111111111",
    fid_trgt_exls_cls_code="0000000000",
    fid_div_cls_code="0",
    fid_rsfl_rate1="0",
    fid_rsfl_rate2="0"
)

#### 7-3. 국내주식 수익자산지표 순위 [v1_국내주식-090]

In [ ]:
##############################################################################################
# [국내주식] 순위분석 > 국내주식 수익자산지표 순위[v1_국내주식-090]
##############################################################################################
ds.profit_asset_index(
    fid_cond_mrkt_div_code="J",
    fid_trgt_cls_code="111111111",
    fid_cond_scr_div_code="20171",
    fid_input_iscd="005930",
    fid_div_cls_code="0",
    fid_input_price_1="0",
    fid_input_price_2="0",
    fid_vol_cnt="0",
    fid_input_option_1="0",
    fid_input_option_2="0",
    fid_rank_sort_cls_code="0",
    fid_blng_cls_code="0",
    fid_trgt_exls_cls_code="0000000000"
)

#### 7-4. 국내주식 시가총액 상위 [v1_국내주식-091]

In [22]:
##############################################################################################
# [국내주식] 순위분석 > 국내주식 시가총액 상위 [v1_국내주식-091]
##############################################################################################
ds.market_cap(
    fid_input_price_2="0",
    fid_cond_mrkt_div_code="J",
    fid_cond_scr_div_code="20171",
    fid_div_cls_code="0",
    fid_input_iscd="005930",
    fid_trgt_cls_code="111111111",
    fid_trgt_exls_cls_code="0000000000",
    fid_input_price_1="0",
    fid_vol_cnt="0"
)

ValueError: 조건 화면 분류 코드 확인요망!!!

#### 7-5. 국내주식 재무비율 순위 [v1_국내주식-092]

In [ ]:
##############################################################################################
# [국내주식] 순위분석 > 국내주식 재무비율 순위[v1_국내주식-092]
##############################################################################################
ds.finance_ratio(
    fid_trgt_cls_code="111111111",
    fid_cond_mrkt_div_code="J",
    fid_cond_scr_div_code="20171",
    fid_input_iscd="005930",
    fid_div_cls_code="0",
    fid_input_price_1="0",
    fid_input_price_2="0",
    fid_vol_cnt="0",
    fid_input_option_1="0",
    fid_input_option_2="0",
    fid_rank_sort_cls_code="0",
    fid_blng_cls_code="0",
    fid_trgt_exls_cls_code="0000000000"
)

#### 7-6. 국내주식 우선주_괴리율 상위 [v1_국내주식-094]

In [ ]:
##############################################################################################
# [국내주식] 순위분석 > 국내주식 우선주_괴리율 상위[v1_국내주식-094]
##############################################################################################
ds.prefer_disparate_ratio(
    fid_vol_cnt="0",
    fid_cond_mrkt_div_code="J",
    fid_cond_scr_div_code="20171",
    fid_div_cls_code="0",
    fid_input_iscd="005930",
    fid_trgt_cls_code="111111111",
    fid_trgt_exls_cls_code="0000000000",
    fid_input_price_1="0",
    fid_input_price_2="0"
)

#### 7-7. 국내주식 이격도 순위 [v1_국내주식-095]

In [ ]:
##############################################################################################
# [국내주식] 순위분석 > 국내주식 이격도 순위 [v1_국내주식-095]
##############################################################################################
ds.disparity(
    fid_input_price_2="0",
    fid_cond_mrkt_div_code="J",
    fid_cond_scr_div_code="20171",
    fid_div_cls_code="0",
    fid_rank_sort_cls_code="0",
    fid_hour_cls_code="0",
    fid_input_iscd="005930",
    fid_trgt_cls_code="111111111",
    fid_trgt_exls_cls_code="0000000000",
    fid_input_price_1="0",
    fid_vol_cnt="0"
)

#### 7-8. 국내주식 시장가치 순위 [v1_국내주식-096]

In [ ]:
##############################################################################################
# [국내주식] 순위분석 > 국내주식 시장가치 순위[v1_국내주식-096]
##############################################################################################
ds.market_value(
    fid_trgt_cls_code="111111111",
    fid_cond_mrkt_div_code="J",
    fid_cond_scr_div_code="20171",
    fid_input_iscd="005930",
    fid_div_cls_code="0",
    fid_input_price_1="0",
    fid_input_price_2="0",
    fid_vol_cnt="0",
    fid_input_option_1="0",
    fid_input_option_2="0",
    fid_rank_sort_cls_code="0",
    fid_blng_cls_code="0",
    fid_trgt_exls_cls_code="0000000000"
)

#### 7-9. 국내주식 체결강도 상위 [v1_국내주식-101]

In [ ]:
##############################################################################################
# [국내주식] 순위분석 > 국내주식 체결강도 상위[v1_국내주식-101]
##############################################################################################
ds.volume_power(
    fid_trgt_exls_cls_code="0000000000",
    fid_cond_mrkt_div_code="J",
    fid_cond_scr_div_code="20171",
    fid_input_iscd="005930",
    fid_div_cls_code="0",
    fid_input_price_1="0",
    fid_input_price_2="0",
    fid_vol_cnt="0",
    fid_trgt_cls_code="111111111"
)

#### 7-10. 국내주식 관심종목등록 상위 [v1_국내주식-102]

In [ ]:
##############################################################################################
# [국내주식] 순위분석 > 국내주식 관심종목등록 상위[v1_국내주식-102]
##############################################################################################
ds.top_interest_stock(
    fid_input_iscd_2="000000",
    fid_cond_mrkt_div_code="J",
    fid_cond_scr_div_code="20171",
    fid_input_iscd="005930",
    fid_trgt_cls_code="111111111",
    fid_trgt_exls_cls_code="0000000000",
    fid_input_price_1="0",
    fid_input_price_2="0",
    fid_vol_cnt="0",
    fid_div_cls_code="0",
    fid_input_cnt_1="0"
)

#### 7-11. 국내주식 예상체결 상승_하락상위 [v1_국내주식-103]

In [ ]:
##############################################################################################
# [국내주식] 순위분석 > 국내주식 예상체결 상승_하락상위[v1_국내주식-103]
##############################################################################################
ds.exp_trans_updown(
    fid_rank_sort_cls_code="0",
    fid_cond_mrkt_div_code="J",
    fid_cond_scr_div_code="20171",
    fid_input_iscd="005930",
    fid_div_cls_code="0",
    fid_aply_rang_prc_1="0",
    fid_vol_cnt="0",
    fid_pbmn="0",
    fid_blng_cls_code="0",
    fid_mkop_cls_code="0"
)

#### 7-12. 국내주식 당사매매종목 상위 [v1_국내주식-104]

In [ ]:
##############################################################################################
# [국내주식] 순위분석 > 국내주식 당사매매종목 상위[v1_국내주식-104]
##############################################################################################
ds.traded_by_company(
    fid_trgt_exls_cls_code="0000000000",
    fid_cond_mrkt_div_code="J",
    fid_cond_scr_div_code="20171",
    fid_div_cls_code="0",
    fid_rank_sort_cls_code="0",
    fid_input_date_1="20250101",
    fid_input_date_2="20260226",
    fid_input_iscd="005930",
    fid_trgt_cls_code="111111111",
    fid_aply_rang_vol="0",
    fid_aply_rang_prc_2="0",
    fid_aply_rang_prc_1="0"
)

#### 7-13. 국내주식 신고_신저근접종목 상위 [v1_국내주식-105]

In [ ]:
##############################################################################################
# [국내주식] 순위분석 > 국내주식 신고_신저근접종목 상위[v1_국내주식-105]
##############################################################################################
ds.near_new_highlow(
    fid_aply_rang_vol="0",
    fid_cond_mrkt_div_code="J",
    fid_cond_scr_div_code="20171",
    fid_div_cls_code="0",
    fid_input_cnt_1="0",
    fid_input_cnt_2="0",
    fid_prc_cls_code="0",
    fid_input_iscd="005930",
    fid_trgt_cls_code="111111111",
    fid_trgt_exls_cls_code="0000000000",
    fid_aply_rang_prc_1="0",
    fid_aply_rang_prc_2="0"
)

#### 7-14. 국내주식 배당률 상위 [국내주식-106]

In [ ]:
##############################################################################################
# [국내주식] 순위분석 > 국내주식 배당률 상위[국내주식-106]
##############################################################################################
ds.dividend_rate(
    cts_area="",
    gb1="0",
    upjong="0",
    gb2="0",
    gb3="0",
    f_dt="20250101",
    t_dt="20260226",
    gb4="0"
)

#### 7-15. 국내주식 대량체결건수 상위 [국내주식-107]

In [ ]:
##############################################################################################
# [국내주식] 순위분석 > 국내주식 대량체결건수 상위[국내주식-107]
##############################################################################################
ds.bulk_trans_num(
    fid_aply_rang_prc_2="0",
    fid_cond_mrkt_div_code="J",
    fid_cond_scr_div_code="20171",
    fid_input_iscd="005930",
    fid_rank_sort_cls_code="0",
    fid_div_cls_code="0",
    fid_input_price_1="0",
    fid_aply_rang_prc_1="0",
    fid_input_iscd_2="000000",
    fid_trgt_exls_cls_code="0000000000",
    fid_trgt_cls_code="111111111",
    fid_vol_cnt="0"
)

#### 7-16. 국내주식 신용잔고 상위 [국내주식-109]

In [ ]:
##############################################################################################
# [국내주식] 순위분석 > 국내주식 신용잔고 상위 [국내주식-109]
##############################################################################################
result1, result2 = ds.credit_balance(
    fid_cond_scr_div_code="20171",
    fid_input_iscd="005930",
    fid_option="0",
    fid_cond_mrkt_div_code="J",
    fid_rank_sort_cls_code="0"
)
print(result1)
print(result2)

#### 7-17. 국내주식 공매도 상위종목 [국내주식-133]

In [ ]:
##############################################################################################
# [국내주식] 순위분석 > 국내주식 공매도 상위종목[국내주식-133]
##############################################################################################
ds.short_sale(
    fid_aply_rang_vol="0",
    fid_cond_mrkt_div_code="J",
    fid_cond_scr_div_code="20171",
    fid_input_iscd="005930",
    fid_period_div_code="D",
    fid_input_cnt_1="0",
    fid_trgt_exls_cls_code="0000000000",
    fid_trgt_cls_code="111111111",
    fid_aply_rang_prc_1="0",
    fid_aply_rang_prc_2="0"
)

#### 7-18. 국내주식 시간외등락율순위 [국내주식-138]

In [ ]:
##############################################################################################
# [국내주식] 순위분석 > 국내주식 시간외등락율순위[국내주식-138]
##############################################################################################
result1, result2 = ds.overtime_fluctuation(
    fid_cond_mrkt_div_code="J",
    fid_mrkt_cls_code="K",
    fid_cond_scr_div_code="20171",
    fid_input_iscd="005930",
    fid_div_cls_code="0",
    fid_input_price_1="0",
    fid_input_price_2="0",
    fid_vol_cnt="0",
    fid_trgt_cls_code="111111111",
    fid_trgt_exls_cls_code="0000000000"
)
print(result1)
print(result2)

#### 7-19. HTS조회상위20종목 [국내주식-214]

In [ ]:
##############################################################################################
# [국내주식] 순위분석 > HTS조회상위20종목[국내주식-214]
##############################################################################################
ds.hts_top_view()

### **8. 실시간시세**

In [ ]:
from kis.domestic_stock import domestic_stock_functions_ws as dsw

ka.auth_ws()
trenv = ka.getTREnv()

# 웹소켓 선언
kws = ka.KISWebSocket(api_url="/tryitout")